// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CapabilitiesInitParameters struct {

	// The ability to add or run anomaly detection. Valid values: DENY.
	AddOrRunAnomalyDetectionForAnalyses *string `json:"addOrRunAnomalyDetectionForAnalyses,omitempty" tf:"add_or_run_anomaly_detection_for_analyses,omitempty"`

	// The ability to create and update email reports. Valid values: DENY.
	CreateAndUpdateDashboardEmailReports *string `json:"createAndUpdateDashboardEmailReports,omitempty" tf:"create_and_update_dashboard_email_reports,omitempty"`

	// The ability to create and update data sources. Valid values: DENY.
	CreateAndUpdateDataSources *string `json:"createAndUpdateDataSources,omitempty" tf:"create_and_update_data_sources,omitempty"`

	// The ability to create and update datasets. Valid values: DENY.
	CreateAndUpdateDatasets *string `json:"createAndUpdateDatasets,omitempty" tf:"create_and_update_datasets,omitempty"`

	// The ability to export to create and update themes. Valid values: DENY.
	CreateAndUpdateThemes *string `json:"createAndUpdateThemes,omitempty" tf:"create_and_update_themes,omitempty"`

	// The ability to create and update threshold alerts. Valid values: DENY.
	CreateAndUpdateThresholdAlerts *string `json:"createAndUpdateThresholdAlerts,omitempty" tf:"create_and_update_threshold_alerts,omitempty"`

	// The ability to create shared folders. Valid values: DENY.
	CreateSharedFolders *string `json:"createSharedFolders,omitempty" tf:"create_shared_folders,omitempty"`

	// The ability to create a SPICE dataset. Valid values: DENY.
	CreateSpiceDataset *string `json:"createSpiceDataset,omitempty" tf:"create_spice_dataset,omitempty"`

	// The ability to export to CSV files from the UI. Valid values: DENY.
	ExportToCsv *string `json:"exportToCsv,omitempty" tf:"export_to_csv,omitempty"`

	// The ability to export to CSV files in scheduled email reports. Valid values: DENY.
	ExportToCsvInScheduledReports *string `json:"exportToCsvInScheduledReports,omitempty" tf:"export_to_csv_in_scheduled_reports,omitempty"`

	// The ability to export to Excel files from the UI. Valid values: DENY.
	ExportToExcel *string `json:"exportToExcel,omitempty" tf:"export_to_excel,omitempty"`

	// The ability to export to Excel files in scheduled email reports. Valid values: DENY.
	ExportToExcelInScheduledReports *string `json:"exportToExcelInScheduledReports,omitempty" tf:"export_to_excel_in_scheduled_reports,omitempty"`

	// The ability to export to PDF files from the UI. Valid values: DENY.
	ExportToPdf *string `json:"exportToPdf,omitempty" tf:"export_to_pdf,omitempty"`

	// The ability to export to PDF files in scheduled email reports. Valid values: DENY.
	ExportToPdfInScheduledReports *string `json:"exportToPdfInScheduledReports,omitempty" tf:"export_to_pdf_in_scheduled_reports,omitempty"`

	// The ability to include content in scheduled email reports. Valid values: DENY.
	IncludeContentInScheduledReportsEmail *string `json:"includeContentInScheduledReportsEmail,omitempty" tf:"include_content_in_scheduled_reports_email,omitempty"`

	// The ability to print reports. Valid values: DENY.
	PrintReports *string `json:"printReports,omitempty" tf:"print_reports,omitempty"`

	// The ability to rename shared folders. Valid values: DENY.
	RenameSharedFolders *string `json:"renameSharedFolders,omitempty" tf:"rename_shared_folders,omitempty"`

	// The ability to share analyses. Valid values: DENY.
	ShareAnalyses *string `json:"shareAnalyses,omitempty" tf:"share_analyses,omitempty"`

	// The ability to share dashboards. Valid values: DENY.
	ShareDashboards *string `json:"shareDashboards,omitempty" tf:"share_dashboards,omitempty"`

	// The ability to share data sources. Valid values: DENY.
	ShareDataSources *string `json:"shareDataSources,omitempty" tf:"share_data_sources,omitempty"`

	// The ability to share datasets. Valid values: DENY.
	ShareDatasets *string `json:"shareDatasets,omitempty" tf:"share_datasets,omitempty"`

	// The ability to subscribe to email reports. Valid values: DENY.
	SubscribeDashboardEmailReports *string `json:"subscribeDashboardEmailReports,omitempty" tf:"subscribe_dashboard_email_reports,omitempty"`

	// The ability to view account SPICE capacity. Valid values: DENY.
	ViewAccountSpiceCapacity *string `json:"viewAccountSpiceCapacity,omitempty" tf:"view_account_spice_capacity,omitempty"`
}

type CapabilitiesObservation struct {

	// The ability to add or run anomaly detection. Valid values: DENY.
	AddOrRunAnomalyDetectionForAnalyses *string `json:"addOrRunAnomalyDetectionForAnalyses,omitempty" tf:"add_or_run_anomaly_detection_for_analyses,omitempty"`

	// The ability to create and update email reports. Valid values: DENY.
	CreateAndUpdateDashboardEmailReports *string `json:"createAndUpdateDashboardEmailReports,omitempty" tf:"create_and_update_dashboard_email_reports,omitempty"`

	// The ability to create and update data sources. Valid values: DENY.
	CreateAndUpdateDataSources *string `json:"createAndUpdateDataSources,omitempty" tf:"create_and_update_data_sources,omitempty"`

	// The ability to create and update datasets. Valid values: DENY.
	CreateAndUpdateDatasets *string `json:"createAndUpdateDatasets,omitempty" tf:"create_and_update_datasets,omitempty"`

	// The ability to export to create and update themes. Valid values: DENY.
	CreateAndUpdateThemes *string `json:"createAndUpdateThemes,omitempty" tf:"create_and_update_themes,omitempty"`

	// The ability to create and update threshold alerts. Valid values: DENY.
	CreateAndUpdateThresholdAlerts *string `json:"createAndUpdateThresholdAlerts,omitempty" tf:"create_and_update_threshold_alerts,omitempty"`

	// The ability to create shared folders. Valid values: DENY.
	CreateSharedFolders *string `json:"createSharedFolders,omitempty" tf:"create_shared_folders,omitempty"`

	// The ability to create a SPICE dataset. Valid values: DENY.
	CreateSpiceDataset *string `json:"createSpiceDataset,omitempty" tf:"create_spice_dataset,omitempty"`

	// The ability to export to CSV files from the UI. Valid values: DENY.
	ExportToCsv *string `json:"exportToCsv,omitempty" tf:"export_to_csv,omitempty"`

	// The ability to export to CSV files in scheduled email reports. Valid values: DENY.
	ExportToCsvInScheduledReports *string `json:"exportToCsvInScheduledReports,omitempty" tf:"export_to_csv_in_scheduled_reports,omitempty"`

	// The ability to export to Excel files from the UI. Valid values: DENY.
	ExportToExcel *string `json:"exportToExcel,omitempty" tf:"export_to_excel,omitempty"`

	// The ability to export to Excel files in scheduled email reports. Valid values: DENY.
	ExportToExcelInScheduledReports *string `json:"exportToExcelInScheduledReports,omitempty" tf:"export_to_excel_in_scheduled_reports,omitempty"`

	// The ability to export to PDF files from the UI. Valid values: DENY.
	ExportToPdf *string `json:"exportToPdf,omitempty" tf:"export_to_pdf,omitempty"`

	// The ability to export to PDF files in scheduled email reports. Valid values: DENY.
	ExportToPdfInScheduledReports *string `json:"exportToPdfInScheduledReports,omitempty" tf:"export_to_pdf_in_scheduled_reports,omitempty"`

	// The ability to include content in scheduled email reports. Valid values: DENY.
	IncludeContentInScheduledReportsEmail *string `json:"includeContentInScheduledReportsEmail,omitempty" tf:"include_content_in_scheduled_reports_email,omitempty"`

	// The ability to print reports. Valid values: DENY.
	PrintReports *string `json:"printReports,omitempty" tf:"print_reports,omitempty"`

	// The ability to rename shared folders. Valid values: DENY.
	RenameSharedFolders *string `json:"renameSharedFolders,omitempty" tf:"rename_shared_folders,omitempty"`

	// The ability to share analyses. Valid values: DENY.
	ShareAnalyses *string `json:"shareAnalyses,omitempty" tf:"share_analyses,omitempty"`

	// The ability to share dashboards. Valid values: DENY.
	ShareDashboards *string `json:"shareDashboards,omitempty" tf:"share_dashboards,omitempty"`

	// The ability to share data sources. Valid values: DENY.
	ShareDataSources *string `json:"shareDataSources,omitempty" tf:"share_data_sources,omitempty"`

	// The ability to share datasets. Valid values: DENY.
	ShareDatasets *string `json:"shareDatasets,omitempty" tf:"share_datasets,omitempty"`

	// The ability to subscribe to email reports. Valid values: DENY.
	SubscribeDashboardEmailReports *string `json:"subscribeDashboardEmailReports,omitempty" tf:"subscribe_dashboard_email_reports,omitempty"`

	// The ability to view account SPICE capacity. Valid values: DENY.
	ViewAccountSpiceCapacity *string `json:"viewAccountSpiceCapacity,omitempty" tf:"view_account_spice_capacity,omitempty"`
}

type CapabilitiesParameters struct {

	// The ability to add or run anomaly detection. Valid values: DENY.
	// +kubebuilder:validation:Optional
	AddOrRunAnomalyDetectionForAnalyses *string `json:"addOrRunAnomalyDetectionForAnalyses,omitempty" tf:"add_or_run_anomaly_detection_for_analyses,omitempty"`

	// The ability to create and update email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateAndUpdateDashboardEmailReports *string `json:"createAndUpdateDashboardEmailReports,omitempty" tf:"create_and_update_dashboard_email_reports,omitempty"`

	// The ability to create and update data sources. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateAndUpdateDataSources *string `json:"createAndUpdateDataSources,omitempty" tf:"create_and_update_data_sources,omitempty"`

	// The ability to create and update datasets. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateAndUpdateDatasets *string `json:"createAndUpdateDatasets,omitempty" tf:"create_and_update_datasets,omitempty"`

	// The ability to export to create and update themes. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateAndUpdateThemes *string `json:"createAndUpdateThemes,omitempty" tf:"create_and_update_themes,omitempty"`

	// The ability to create and update threshold alerts. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateAndUpdateThresholdAlerts *string `json:"createAndUpdateThresholdAlerts,omitempty" tf:"create_and_update_threshold_alerts,omitempty"`

	// The ability to create shared folders. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateSharedFolders *string `json:"createSharedFolders,omitempty" tf:"create_shared_folders,omitempty"`

	// The ability to create a SPICE dataset. Valid values: DENY.
	// +kubebuilder:validation:Optional
	CreateSpiceDataset *string `json:"createSpiceDataset,omitempty" tf:"create_spice_dataset,omitempty"`

	// The ability to export to CSV files from the UI. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToCsv *string `json:"exportToCsv,omitempty" tf:"export_to_csv,omitempty"`

	// The ability to export to CSV files in scheduled email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToCsvInScheduledReports *string `json:"exportToCsvInScheduledReports,omitempty" tf:"export_to_csv_in_scheduled_reports,omitempty"`

	// The ability to export to Excel files from the UI. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToExcel *string `json:"exportToExcel,omitempty" tf:"export_to_excel,omitempty"`

	// The ability to export to Excel files in scheduled email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToExcelInScheduledReports *string `json:"exportToExcelInScheduledReports,omitempty" tf:"export_to_excel_in_scheduled_reports,omitempty"`

	// The ability to export to PDF files from the UI. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToPdf *string `json:"exportToPdf,omitempty" tf:"export_to_pdf,omitempty"`

	// The ability to export to PDF files in scheduled email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ExportToPdfInScheduledReports *string `json:"exportToPdfInScheduledReports,omitempty" tf:"export_to_pdf_in_scheduled_reports,omitempty"`

	// The ability to include content in scheduled email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	IncludeContentInScheduledReportsEmail *string `json:"includeContentInScheduledReportsEmail,omitempty" tf:"include_content_in_scheduled_reports_email,omitempty"`

	// The ability to print reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	PrintReports *string `json:"printReports,omitempty" tf:"print_reports,omitempty"`

	// The ability to rename shared folders. Valid values: DENY.
	// +kubebuilder:validation:Optional
	RenameSharedFolders *string `json:"renameSharedFolders,omitempty" tf:"rename_shared_folders,omitempty"`

	// The ability to share analyses. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ShareAnalyses *string `json:"shareAnalyses,omitempty" tf:"share_analyses,omitempty"`

	// The ability to share dashboards. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ShareDashboards *string `json:"shareDashboards,omitempty" tf:"share_dashboards,omitempty"`

	// The ability to share data sources. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ShareDataSources *string `json:"shareDataSources,omitempty" tf:"share_data_sources,omitempty"`

	// The ability to share datasets. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ShareDatasets *string `json:"shareDatasets,omitempty" tf:"share_datasets,omitempty"`

	// The ability to subscribe to email reports. Valid values: DENY.
	// +kubebuilder:validation:Optional
	SubscribeDashboardEmailReports *string `json:"subscribeDashboardEmailReports,omitempty" tf:"subscribe_dashboard_email_reports,omitempty"`

	// The ability to view account SPICE capacity. Valid values: DENY.
	// +kubebuilder:validation:Optional
	ViewAccountSpiceCapacity *string `json:"viewAccountSpiceCapacity,omitempty" tf:"view_account_spice_capacity,omitempty"`
}

type CustomPermissionsInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Actions to include in the custom permissions profile. See capabilities.
	Capabilities *CapabilitiesInitParameters `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type CustomPermissionsObservation struct {

	// ARN of the custom permissions profile.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Actions to include in the custom permissions profile. See capabilities.
	Capabilities *CapabilitiesObservation `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// Custom permissions profile name.
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type CustomPermissionsParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Actions to include in the custom permissions profile. See capabilities.
	// +kubebuilder:validation:Optional
	Capabilities *CapabilitiesParameters `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// Custom permissions profile name.
	// +kubebuilder:validation:Required
	CustomPermissionsName *string `json:"customPermissionsName" tf:"custom_permissions_name,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// CustomPermissionsSpec defines the desired state of CustomPermissions
type CustomPermissionsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomPermissionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomPermissionsInitParameters `json:"initProvider,omitempty"`
}

// CustomPermissionsStatus defines the observed state of CustomPermissions.
type CustomPermissionsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomPermissionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomPermissions is the Schema for the CustomPermissionss API. Manages a QuickSight custom permissions profile.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type CustomPermissions struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CustomPermissionsSpec   `json:"spec"`
	Status            CustomPermissionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomPermissionsList contains a list of CustomPermissionss
type CustomPermissionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomPermissions `json:"items"`
}

// Repository type metadata.
var (
	CustomPermissions_Kind             = "CustomPermissions"
	CustomPermissions_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomPermissions_Kind}.String()
	CustomPermissions_KindAPIVersion   = CustomPermissions_Kind + "." + CRDGroupVersion.String()
	CustomPermissions_GroupVersionKind = CRDGroupVersion.WithKind(CustomPermissions_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomPermissions{}, &CustomPermissionsList{})
}
