// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FolderMembershipInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Identifier for the folder.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Folder
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("folder_id",false)
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// Reference to a Folder in quicksight to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDRef *v1.Reference `json:"folderIdRef,omitempty" tf:"-"`

	// Selector for a Folder in quicksight to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDSelector *v1.Selector `json:"folderIdSelector,omitempty" tf:"-"`

	// ID of the asset (the dashboard, analysis, or dataset).
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// Reference to a DataSet in quicksight to populate memberId.
	// +kubebuilder:validation:Optional
	MemberIDRef *v1.Reference `json:"memberIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate memberId.
	// +kubebuilder:validation:Optional
	MemberIDSelector *v1.Selector `json:"memberIdSelector,omitempty" tf:"-"`

	// Type of the member. Valid values are ANALYSIS, DASHBOARD, and DATASET.
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`
}

type FolderMembershipObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Identifier for the folder.
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// A comma-delimited string joining AWS account ID, folder ID, member type, and member ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of the asset (the dashboard, analysis, or dataset).
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// Type of the member. Valid values are ANALYSIS, DASHBOARD, and DATASET.
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type FolderMembershipParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Identifier for the folder.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Folder
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("folder_id",false)
	// +kubebuilder:validation:Optional
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// Reference to a Folder in quicksight to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDRef *v1.Reference `json:"folderIdRef,omitempty" tf:"-"`

	// Selector for a Folder in quicksight to populate folderId.
	// +kubebuilder:validation:Optional
	FolderIDSelector *v1.Selector `json:"folderIdSelector,omitempty" tf:"-"`

	// ID of the asset (the dashboard, analysis, or dataset).
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	// +kubebuilder:validation:Optional
	MemberID *string `json:"memberId,omitempty" tf:"member_id,omitempty"`

	// Reference to a DataSet in quicksight to populate memberId.
	// +kubebuilder:validation:Optional
	MemberIDRef *v1.Reference `json:"memberIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate memberId.
	// +kubebuilder:validation:Optional
	MemberIDSelector *v1.Selector `json:"memberIdSelector,omitempty" tf:"-"`

	// Type of the member. Valid values are ANALYSIS, DASHBOARD, and DATASET.
	// +kubebuilder:validation:Optional
	MemberType *string `json:"memberType,omitempty" tf:"member_type,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

// FolderMembershipSpec defines the desired state of FolderMembership
type FolderMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FolderMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FolderMembershipInitParameters `json:"initProvider,omitempty"`
}

// FolderMembershipStatus defines the observed state of FolderMembership.
type FolderMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FolderMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FolderMembership is the Schema for the FolderMemberships API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type FolderMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.memberType) || (has(self.initProvider) && has(self.initProvider.memberType))",message="spec.forProvider.memberType is a required parameter"
	Spec   FolderMembershipSpec   `json:"spec"`
	Status FolderMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FolderMembershipList contains a list of FolderMemberships
type FolderMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FolderMembership `json:"items"`
}

// Repository type metadata.
var (
	FolderMembership_Kind             = "FolderMembership"
	FolderMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FolderMembership_Kind}.String()
	FolderMembership_KindAPIVersion   = FolderMembership_Kind + "." + CRDGroupVersion.String()
	FolderMembership_GroupVersionKind = CRDGroupVersion.WithKind(FolderMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&FolderMembership{}, &FolderMembershipList{})
}
