// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RoleCustomPermissionInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Custom permissions profile name.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.CustomPermissions
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	// Reference to a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameRef *v1.Reference `json:"customPermissionsNameRef,omitempty" tf:"-"`

	// Selector for a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameSelector *v1.Selector `json:"customPermissionsNameSelector,omitempty" tf:"-"`

	// Namespace containing the role. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type RoleCustomPermissionObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Custom permissions profile name.
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Namespace containing the role. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Role. Valid values are ADMIN, AUTHOR, READER, ADMIN_PRO, AUTHOR_PRO, and READER_PRO.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RoleCustomPermissionParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Custom permissions profile name.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.CustomPermissions
	// +kubebuilder:validation:Optional
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	// Reference to a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameRef *v1.Reference `json:"customPermissionsNameRef,omitempty" tf:"-"`

	// Selector for a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameSelector *v1.Selector `json:"customPermissionsNameSelector,omitempty" tf:"-"`

	// Namespace containing the role. Defaults to default.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Role. Valid values are ADMIN, AUTHOR, READER, ADMIN_PRO, AUTHOR_PRO, and READER_PRO.
	// +kubebuilder:validation:Required
	Role *string `json:"role" tf:"role,omitempty"`
}

// RoleCustomPermissionSpec defines the desired state of RoleCustomPermission
type RoleCustomPermissionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RoleCustomPermissionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleCustomPermissionInitParameters `json:"initProvider,omitempty"`
}

// RoleCustomPermissionStatus defines the observed state of RoleCustomPermission.
type RoleCustomPermissionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleCustomPermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoleCustomPermission is the Schema for the RoleCustomPermissions API. Manages the custom permissions that are associated with a role.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type RoleCustomPermission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RoleCustomPermissionSpec   `json:"spec"`
	Status            RoleCustomPermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleCustomPermissionList contains a list of RoleCustomPermissions
type RoleCustomPermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleCustomPermission `json:"items"`
}

// Repository type metadata.
var (
	RoleCustomPermission_Kind             = "RoleCustomPermission"
	RoleCustomPermission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleCustomPermission_Kind}.String()
	RoleCustomPermission_KindAPIVersion   = RoleCustomPermission_Kind + "." + CRDGroupVersion.String()
	RoleCustomPermission_GroupVersionKind = CRDGroupVersion.WithKind(RoleCustomPermission_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleCustomPermission{}, &RoleCustomPermissionList{})
}
