// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type RefreshOnDayInitParameters struct {

	// The day of the month that you want to schedule refresh on.
	DayOfMonth *string `json:"dayOfMonth,omitempty" tf:"day_of_month,omitempty"`

	// The day of the week that you want to schedule a refresh on. Valid values are SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY and SATURDAY.
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`
}

type RefreshOnDayObservation struct {

	// The day of the month that you want to schedule refresh on.
	DayOfMonth *string `json:"dayOfMonth,omitempty" tf:"day_of_month,omitempty"`

	// The day of the week that you want to schedule a refresh on. Valid values are SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY and SATURDAY.
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`
}

type RefreshOnDayParameters struct {

	// The day of the month that you want to schedule refresh on.
	// +kubebuilder:validation:Optional
	DayOfMonth *string `json:"dayOfMonth,omitempty" tf:"day_of_month,omitempty"`

	// The day of the week that you want to schedule a refresh on. Valid values are SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY and SATURDAY.
	// +kubebuilder:validation:Optional
	DayOfWeek *string `json:"dayOfWeek,omitempty" tf:"day_of_week,omitempty"`
}

type RefreshScheduleInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the dataset.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDRef *v1.Reference `json:"dataSetIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDSelector *v1.Selector `json:"dataSetIdSelector,omitempty" tf:"-"`

	// The refresh schedule. See schedule
	Schedule *ScheduleInitParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type RefreshScheduleObservation struct {

	// Amazon Resource Name (ARN) of the refresh schedule.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the dataset.
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// A comma-delimited string joining AWS account ID, data set ID & refresh schedule ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The refresh schedule. See schedule
	Schedule *ScheduleObservation `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type RefreshScheduleParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the dataset.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	// +kubebuilder:validation:Optional
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDRef *v1.Reference `json:"dataSetIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDSelector *v1.Selector `json:"dataSetIdSelector,omitempty" tf:"-"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// The refresh schedule. See schedule
	// +kubebuilder:validation:Optional
	Schedule *ScheduleParameters `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type ScheduleFrequencyInitParameters struct {

	// The interval between scheduled refreshes. Valid values are MINUTE15, MINUTE30, HOURLY, DAILY, WEEKLY and MONTHLY.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// The refresh on entity configuration for weekly or monthly schedules. See refresh_on_day.
	RefreshOnDay *RefreshOnDayInitParameters `json:"refreshOnDay,omitempty" tf:"refresh_on_day,omitempty"`

	// The time of day that you want the dataset to refresh. This value is expressed in HH:MM format. This field is not required for schedules that refresh hourly.
	TimeOfTheDay *string `json:"timeOfTheDay,omitempty" tf:"time_of_the_day,omitempty"`

	// The timezone that you want the refresh schedule to use.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleFrequencyObservation struct {

	// The interval between scheduled refreshes. Valid values are MINUTE15, MINUTE30, HOURLY, DAILY, WEEKLY and MONTHLY.
	Interval *string `json:"interval,omitempty" tf:"interval,omitempty"`

	// The refresh on entity configuration for weekly or monthly schedules. See refresh_on_day.
	RefreshOnDay *RefreshOnDayObservation `json:"refreshOnDay,omitempty" tf:"refresh_on_day,omitempty"`

	// The time of day that you want the dataset to refresh. This value is expressed in HH:MM format. This field is not required for schedules that refresh hourly.
	TimeOfTheDay *string `json:"timeOfTheDay,omitempty" tf:"time_of_the_day,omitempty"`

	// The timezone that you want the refresh schedule to use.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleFrequencyParameters struct {

	// The interval between scheduled refreshes. Valid values are MINUTE15, MINUTE30, HOURLY, DAILY, WEEKLY and MONTHLY.
	// +kubebuilder:validation:Optional
	Interval *string `json:"interval" tf:"interval,omitempty"`

	// The refresh on entity configuration for weekly or monthly schedules. See refresh_on_day.
	// +kubebuilder:validation:Optional
	RefreshOnDay *RefreshOnDayParameters `json:"refreshOnDay,omitempty" tf:"refresh_on_day,omitempty"`

	// The time of day that you want the dataset to refresh. This value is expressed in HH:MM format. This field is not required for schedules that refresh hourly.
	// +kubebuilder:validation:Optional
	TimeOfTheDay *string `json:"timeOfTheDay,omitempty" tf:"time_of_the_day,omitempty"`

	// The timezone that you want the refresh schedule to use.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`
}

type ScheduleInitParameters struct {

	// The type of refresh that the dataset undergoes. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	RefreshType *string `json:"refreshType,omitempty" tf:"refresh_type,omitempty"`

	// The configuration of the schedule frequency. See schedule_frequency.
	ScheduleFrequency *ScheduleFrequencyInitParameters `json:"scheduleFrequency,omitempty" tf:"schedule_frequency,omitempty"`

	// MM-DDTHH:MM:SS format.
	StartAfterDateTime *string `json:"startAfterDateTime,omitempty" tf:"start_after_date_time,omitempty"`
}

type ScheduleObservation struct {

	// The type of refresh that the dataset undergoes. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	RefreshType *string `json:"refreshType,omitempty" tf:"refresh_type,omitempty"`

	// The configuration of the schedule frequency. See schedule_frequency.
	ScheduleFrequency *ScheduleFrequencyObservation `json:"scheduleFrequency,omitempty" tf:"schedule_frequency,omitempty"`

	// MM-DDTHH:MM:SS format.
	StartAfterDateTime *string `json:"startAfterDateTime,omitempty" tf:"start_after_date_time,omitempty"`
}

type ScheduleParameters struct {

	// The type of refresh that the dataset undergoes. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	// +kubebuilder:validation:Optional
	RefreshType *string `json:"refreshType" tf:"refresh_type,omitempty"`

	// The configuration of the schedule frequency. See schedule_frequency.
	// +kubebuilder:validation:Optional
	ScheduleFrequency *ScheduleFrequencyParameters `json:"scheduleFrequency,omitempty" tf:"schedule_frequency,omitempty"`

	// MM-DDTHH:MM:SS format.
	// +kubebuilder:validation:Optional
	StartAfterDateTime *string `json:"startAfterDateTime,omitempty" tf:"start_after_date_time,omitempty"`
}

// RefreshScheduleSpec defines the desired state of RefreshSchedule
type RefreshScheduleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RefreshScheduleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RefreshScheduleInitParameters `json:"initProvider,omitempty"`
}

// RefreshScheduleStatus defines the observed state of RefreshSchedule.
type RefreshScheduleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RefreshScheduleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RefreshSchedule is the Schema for the RefreshSchedules API. Manages a Resource QuickSight Refresh Schedule.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type RefreshSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RefreshScheduleSpec   `json:"spec"`
	Status            RefreshScheduleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RefreshScheduleList contains a list of RefreshSchedules
type RefreshScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RefreshSchedule `json:"items"`
}

// Repository type metadata.
var (
	RefreshSchedule_Kind             = "RefreshSchedule"
	RefreshSchedule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RefreshSchedule_Kind}.String()
	RefreshSchedule_KindAPIVersion   = RefreshSchedule_Kind + "." + CRDGroupVersion.String()
	RefreshSchedule_GroupVersionKind = CRDGroupVersion.WithKind(RefreshSchedule_Kind)
)

func init() {
	SchemeBuilder.Register(&RefreshSchedule{}, &RefreshScheduleList{})
}
