// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SourceAnalysisDataSetReferencesInitParameters struct {

	// Dataset Amazon Resource Name (ARN).
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	DataSetArn *string `json:"dataSetArn,omitempty" tf:"data_set_arn,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetArn.
	// +kubebuilder:validation:Optional
	DataSetArnRef *v1.Reference `json:"dataSetArnRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetArn.
	// +kubebuilder:validation:Optional
	DataSetArnSelector *v1.Selector `json:"dataSetArnSelector,omitempty" tf:"-"`

	// Dataset placeholder.
	DataSetPlaceholder *string `json:"dataSetPlaceholder,omitempty" tf:"data_set_placeholder,omitempty"`
}

type SourceAnalysisDataSetReferencesObservation struct {

	// Dataset Amazon Resource Name (ARN).
	DataSetArn *string `json:"dataSetArn,omitempty" tf:"data_set_arn,omitempty"`

	// Dataset placeholder.
	DataSetPlaceholder *string `json:"dataSetPlaceholder,omitempty" tf:"data_set_placeholder,omitempty"`
}

type SourceAnalysisDataSetReferencesParameters struct {

	// Dataset Amazon Resource Name (ARN).
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	DataSetArn *string `json:"dataSetArn,omitempty" tf:"data_set_arn,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetArn.
	// +kubebuilder:validation:Optional
	DataSetArnRef *v1.Reference `json:"dataSetArnRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetArn.
	// +kubebuilder:validation:Optional
	DataSetArnSelector *v1.Selector `json:"dataSetArnSelector,omitempty" tf:"-"`

	// Dataset placeholder.
	// +kubebuilder:validation:Optional
	DataSetPlaceholder *string `json:"dataSetPlaceholder" tf:"data_set_placeholder,omitempty"`
}

type SourceAnalysisInitParameters struct {

	// The Amazon Resource Name (ARN) of the resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Analysis
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Analysis in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.Reference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Analysis in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.Selector `json:"arnSelector,omitempty" tf:"-"`

	// A list of dataset references used as placeholders in the template. See data_set_references.
	DataSetReferences []SourceAnalysisDataSetReferencesInitParameters `json:"dataSetReferences,omitempty" tf:"data_set_references,omitempty"`
}

type SourceAnalysisObservation struct {

	// The Amazon Resource Name (ARN) of the resource.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// A list of dataset references used as placeholders in the template. See data_set_references.
	DataSetReferences []SourceAnalysisDataSetReferencesObservation `json:"dataSetReferences,omitempty" tf:"data_set_references,omitempty"`
}

type SourceAnalysisParameters struct {

	// The Amazon Resource Name (ARN) of the resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Analysis
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Analysis in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.Reference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Analysis in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.Selector `json:"arnSelector,omitempty" tf:"-"`

	// A list of dataset references used as placeholders in the template. See data_set_references.
	// +kubebuilder:validation:Optional
	DataSetReferences []SourceAnalysisDataSetReferencesParameters `json:"dataSetReferences" tf:"data_set_references,omitempty"`
}

type TemplateInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Display name for the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the template. Maximum of 64 items. See permissions.
	Permissions []TemplatePermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// The entity that you are using as a source when you create the template (analysis or template). Only one of definition or source_entity should be configured. See source_entity.
	SourceEntity *TemplateSourceEntityInitParameters `json:"sourceEntity,omitempty" tf:"source_entity,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Identifier for the template.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// A description of the current template version being created/updated.
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`
}

type TemplateObservation struct {

	// ARN of the template.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The time that the template was created.
	CreatedTime *string `json:"createdTime,omitempty" tf:"created_time,omitempty"`

	// A comma-delimited string joining AWS account ID and template ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The time that the template was last updated.
	LastUpdatedTime *string `json:"lastUpdatedTime,omitempty" tf:"last_updated_time,omitempty"`

	// Display name for the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the template. Maximum of 64 items. See permissions.
	Permissions []TemplatePermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The entity that you are using as a source when you create the template (analysis or template). Only one of definition or source_entity should be configured. See source_entity.
	SourceEntity *TemplateSourceEntityObservation `json:"sourceEntity,omitempty" tf:"source_entity,omitempty"`

	// Amazon Resource Name (ARN) of an analysis or template that was used to create this template.
	SourceEntityArn *string `json:"sourceEntityArn,omitempty" tf:"source_entity_arn,omitempty"`

	// The template creation status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// Identifier for the template.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// A description of the current template version being created/updated.
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`

	// The version number of the template version.
	VersionNumber *float64 `json:"versionNumber,omitempty" tf:"version_number,omitempty"`
}

type TemplateParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Display name for the template.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the template. Maximum of 64 items. See permissions.
	// +kubebuilder:validation:Optional
	Permissions []TemplatePermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// The entity that you are using as a source when you create the template (analysis or template). Only one of definition or source_entity should be configured. See source_entity.
	// +kubebuilder:validation:Optional
	SourceEntity *TemplateSourceEntityParameters `json:"sourceEntity,omitempty" tf:"source_entity,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Identifier for the template.
	// +kubebuilder:validation:Optional
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// A description of the current template version being created/updated.
	// +kubebuilder:validation:Optional
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`
}

type TemplatePermissionsInitParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`
}

type TemplatePermissionsObservation struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`
}

type TemplatePermissionsParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal" tf:"principal,omitempty"`
}

type TemplateSourceEntityInitParameters struct {

	// The source analysis, if it is based on an analysis.. Only one of source_analysis or source_template should be configured. See source_analysis.
	SourceAnalysis *SourceAnalysisInitParameters `json:"sourceAnalysis,omitempty" tf:"source_analysis,omitempty"`

	// The source template, if it is based on an template.. Only one of source_analysis or source_template should be configured. See source_template.
	SourceTemplate *TemplateSourceEntitySourceTemplateInitParameters `json:"sourceTemplate,omitempty" tf:"source_template,omitempty"`
}

type TemplateSourceEntityObservation struct {

	// The source analysis, if it is based on an analysis.. Only one of source_analysis or source_template should be configured. See source_analysis.
	SourceAnalysis *SourceAnalysisObservation `json:"sourceAnalysis,omitempty" tf:"source_analysis,omitempty"`

	// The source template, if it is based on an template.. Only one of source_analysis or source_template should be configured. See source_template.
	SourceTemplate *TemplateSourceEntitySourceTemplateObservation `json:"sourceTemplate,omitempty" tf:"source_template,omitempty"`
}

type TemplateSourceEntityParameters struct {

	// The source analysis, if it is based on an analysis.. Only one of source_analysis or source_template should be configured. See source_analysis.
	// +kubebuilder:validation:Optional
	SourceAnalysis *SourceAnalysisParameters `json:"sourceAnalysis,omitempty" tf:"source_analysis,omitempty"`

	// The source template, if it is based on an template.. Only one of source_analysis or source_template should be configured. See source_template.
	// +kubebuilder:validation:Optional
	SourceTemplate *TemplateSourceEntitySourceTemplateParameters `json:"sourceTemplate,omitempty" tf:"source_template,omitempty"`
}

type TemplateSourceEntitySourceTemplateInitParameters struct {

	// The Amazon Resource Name (ARN) of the resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Template in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.Reference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.Selector `json:"arnSelector,omitempty" tf:"-"`
}

type TemplateSourceEntitySourceTemplateObservation struct {

	// The Amazon Resource Name (ARN) of the resource.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`
}

type TemplateSourceEntitySourceTemplateParameters struct {

	// The Amazon Resource Name (ARN) of the resource.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/cluster/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Reference to a Template in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnRef *v1.Reference `json:"arnRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate arn.
	// +kubebuilder:validation:Optional
	ArnSelector *v1.Selector `json:"arnSelector,omitempty" tf:"-"`
}

// TemplateSpec defines the desired state of Template
type TemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TemplateInitParameters `json:"initProvider,omitempty"`
}

// TemplateStatus defines the observed state of Template.
type TemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Template is the Schema for the Templates API. Creates a QuickSight Template resource. The 'definition' field is not supported due to Kubernetes CRD size limitations with deeply nested fields.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type Template struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.templateId) || (has(self.initProvider) && has(self.initProvider.templateId))",message="spec.forProvider.templateId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.versionDescription) || (has(self.initProvider) && has(self.initProvider.versionDescription))",message="spec.forProvider.versionDescription is a required parameter"
	Spec   TemplateSpec   `json:"spec"`
	Status TemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TemplateList contains a list of Templates
type TemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Template `json:"items"`
}

// Repository type metadata.
var (
	Template_Kind             = "Template"
	Template_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Template_Kind}.String()
	Template_KindAPIVersion   = Template_Kind + "." + CRDGroupVersion.String()
	Template_GroupVersionKind = CRDGroupVersion.WithKind(Template_Kind)
)

func init() {
	SchemeBuilder.Register(&Template{}, &TemplateList{})
}
