// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TemplateAliasInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// ID of the template.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("template_id",false)
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// Reference to a Template in quicksight to populate templateId.
	// +kubebuilder:validation:Optional
	TemplateIDRef *v1.Reference `json:"templateIdRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate templateId.
	// +kubebuilder:validation:Optional
	TemplateIDSelector *v1.Selector `json:"templateIdSelector,omitempty" tf:"-"`

	// Version number of the template.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("version_number",true)
	TemplateVersionNumber *float64 `json:"templateVersionNumber,omitempty" tf:"template_version_number,omitempty"`

	// Reference to a Template in quicksight to populate templateVersionNumber.
	// +kubebuilder:validation:Optional
	TemplateVersionNumberRef *v1.Reference `json:"templateVersionNumberRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate templateVersionNumber.
	// +kubebuilder:validation:Optional
	TemplateVersionNumberSelector *v1.Selector `json:"templateVersionNumberSelector,omitempty" tf:"-"`
}

type TemplateAliasObservation struct {

	// Amazon Resource Name (ARN) of the template alias.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// A comma-delimited string joining AWS account ID, template ID, and alias name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// ID of the template.
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// Version number of the template.
	TemplateVersionNumber *float64 `json:"templateVersionNumber,omitempty" tf:"template_version_number,omitempty"`
}

type TemplateAliasParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// ID of the template.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("template_id",false)
	// +kubebuilder:validation:Optional
	TemplateID *string `json:"templateId,omitempty" tf:"template_id,omitempty"`

	// Reference to a Template in quicksight to populate templateId.
	// +kubebuilder:validation:Optional
	TemplateIDRef *v1.Reference `json:"templateIdRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate templateId.
	// +kubebuilder:validation:Optional
	TemplateIDSelector *v1.Selector `json:"templateIdSelector,omitempty" tf:"-"`

	// Version number of the template.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.Template
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("version_number",true)
	// +kubebuilder:validation:Optional
	TemplateVersionNumber *float64 `json:"templateVersionNumber,omitempty" tf:"template_version_number,omitempty"`

	// Reference to a Template in quicksight to populate templateVersionNumber.
	// +kubebuilder:validation:Optional
	TemplateVersionNumberRef *v1.Reference `json:"templateVersionNumberRef,omitempty" tf:"-"`

	// Selector for a Template in quicksight to populate templateVersionNumber.
	// +kubebuilder:validation:Optional
	TemplateVersionNumberSelector *v1.Selector `json:"templateVersionNumberSelector,omitempty" tf:"-"`
}

// TemplateAliasSpec defines the desired state of TemplateAlias
type TemplateAliasSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TemplateAliasParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TemplateAliasInitParameters `json:"initProvider,omitempty"`
}

// TemplateAliasStatus defines the observed state of TemplateAlias.
type TemplateAliasStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TemplateAliasObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TemplateAlias is the Schema for the TemplateAliass API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type TemplateAlias struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TemplateAliasSpec   `json:"spec"`
	Status            TemplateAliasStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TemplateAliasList contains a list of TemplateAliass
type TemplateAliasList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TemplateAlias `json:"items"`
}

// Repository type metadata.
var (
	TemplateAlias_Kind             = "TemplateAlias"
	TemplateAlias_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TemplateAlias_Kind}.String()
	TemplateAlias_KindAPIVersion   = TemplateAlias_Kind + "." + CRDGroupVersion.String()
	TemplateAlias_GroupVersionKind = CRDGroupVersion.WithKind(TemplateAlias_Kind)
)

func init() {
	SchemeBuilder.Register(&TemplateAlias{}, &TemplateAliasList{})
}
