// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type UserCustomPermissionInitParameters struct {

	// Custom permissions profile name.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.CustomPermissions
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	// Reference to a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameRef *v1.Reference `json:"customPermissionsNameRef,omitempty" tf:"-"`

	// Selector for a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameSelector *v1.Selector `json:"customPermissionsNameSelector,omitempty" tf:"-"`
}

type UserCustomPermissionObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Custom permissions profile name.
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Namespace that the user belongs to. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Username of the user.
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type UserCustomPermissionParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Custom permissions profile name.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.CustomPermissions
	// +kubebuilder:validation:Optional
	CustomPermissionsName *string `json:"customPermissionsName,omitempty" tf:"custom_permissions_name,omitempty"`

	// Reference to a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameRef *v1.Reference `json:"customPermissionsNameRef,omitempty" tf:"-"`

	// Selector for a CustomPermissions in quicksight to populate customPermissionsName.
	// +kubebuilder:validation:Optional
	CustomPermissionsNameSelector *v1.Selector `json:"customPermissionsNameSelector,omitempty" tf:"-"`

	// Namespace that the user belongs to. Defaults to default.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Username of the user.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/cluster/quicksight/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("user_name",false)
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`

	// Reference to a User in quicksight to populate userName.
	// +kubebuilder:validation:Optional
	UserNameRef *v1.Reference `json:"userNameRef,omitempty" tf:"-"`

	// Selector for a User in quicksight to populate userName.
	// +kubebuilder:validation:Optional
	UserNameSelector *v1.Selector `json:"userNameSelector,omitempty" tf:"-"`
}

// UserCustomPermissionSpec defines the desired state of UserCustomPermission
type UserCustomPermissionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UserCustomPermissionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider UserCustomPermissionInitParameters `json:"initProvider,omitempty"`
}

// UserCustomPermissionStatus defines the observed state of UserCustomPermission.
type UserCustomPermissionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UserCustomPermissionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// UserCustomPermission is the Schema for the UserCustomPermissions API. Manages the custom permissions profile for a user.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type UserCustomPermission struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              UserCustomPermissionSpec   `json:"spec"`
	Status            UserCustomPermissionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UserCustomPermissionList contains a list of UserCustomPermissions
type UserCustomPermissionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UserCustomPermission `json:"items"`
}

// Repository type metadata.
var (
	UserCustomPermission_Kind             = "UserCustomPermission"
	UserCustomPermission_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UserCustomPermission_Kind}.String()
	UserCustomPermission_KindAPIVersion   = UserCustomPermission_Kind + "." + CRDGroupVersion.String()
	UserCustomPermission_GroupVersionKind = CRDGroupVersion.WithKind(UserCustomPermission_Kind)
)

func init() {
	SchemeBuilder.Register(&UserCustomPermission{}, &UserCustomPermissionList{})
}
