# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: IPRestriction
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/iprestriction
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    enabled: true
    ipRestrictionRuleMap:
      108.56.166.202/32: Allow self
    region: us-west-1
    vpcIdRestrictionRuleMap:
      ${(aws_vpc.example.id)}: Main VPC
