# SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: CC0-1.0


apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: Theme
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/theme
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    baseThemeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    configuration:
      dataColorPalette:
        colors:
        - '#FFFFFF'
        - '#111111'
        - '#222222'
        - '#333333'
        - '#444444'
        - '#555555'
        - '#666666'
        - '#777777'
        - '#888888'
        - '#999999'
        emptyFillColor: '#FFFFFF'
        minMaxGradient:
        - '#FFFFFF'
        - '#111111'
    name: example
    region: us-west-1
    themeId: example
