// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccountSettingsInitParameters struct {

	// The default namespace for this Amazon Web Services account. Currently, the default is default.
	DefaultNamespace *string `json:"defaultNamespace,omitempty" tf:"default_namespace,omitempty"`

	// A boolean value that determines whether or not an Amazon QuickSight account can be deleted. If true, it does not allow the account to be deleted and results in an error message if a user tries to make a DeleteAccountSubscription request. If false, it will allow the account to be deleted.
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty" tf:"termination_protection_enabled,omitempty"`
}

type AccountSettingsObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The default namespace for this Amazon Web Services account. Currently, the default is default.
	DefaultNamespace *string `json:"defaultNamespace,omitempty" tf:"default_namespace,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// A boolean value that determines whether or not an Amazon QuickSight account can be deleted. If true, it does not allow the account to be deleted and results in an error message if a user tries to make a DeleteAccountSubscription request. If false, it will allow the account to be deleted.
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty" tf:"termination_protection_enabled,omitempty"`
}

type AccountSettingsParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The default namespace for this Amazon Web Services account. Currently, the default is default.
	// +kubebuilder:validation:Optional
	DefaultNamespace *string `json:"defaultNamespace,omitempty" tf:"default_namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// A boolean value that determines whether or not an Amazon QuickSight account can be deleted. If true, it does not allow the account to be deleted and results in an error message if a user tries to make a DeleteAccountSubscription request. If false, it will allow the account to be deleted.
	// +kubebuilder:validation:Optional
	TerminationProtectionEnabled *bool `json:"terminationProtectionEnabled,omitempty" tf:"termination_protection_enabled,omitempty"`
}

// AccountSettingsSpec defines the desired state of AccountSettings
type AccountSettingsSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccountSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountSettingsInitParameters `json:"initProvider,omitempty"`
}

// AccountSettingsStatus defines the observed state of AccountSettings.
type AccountSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountSettings is the Schema for the AccountSettingss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type AccountSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              AccountSettingsSpec   `json:"spec"`
	Status            AccountSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountSettingsList contains a list of AccountSettingss
type AccountSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountSettings `json:"items"`
}

// Repository type metadata.
var (
	AccountSettings_Kind             = "AccountSettings"
	AccountSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountSettings_Kind}.String()
	AccountSettings_KindAPIVersion   = AccountSettings_Kind + "." + CRDGroupVersion.String()
	AccountSettings_GroupVersionKind = CRDGroupVersion.WithKind(AccountSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountSettings{}, &AccountSettingsList{})
}
