// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FolderInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Identifier for the folder.
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// The type of folder. By default, it is SHARED. Valid values are: SHARED.
	FolderType *string `json:"folderType,omitempty" tf:"folder_type,omitempty"`

	// Display name for the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Amazon Resource Name (ARN) for the parent folder. If not set, creates a root-level folder.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Folder
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	ParentFolderArn *string `json:"parentFolderArn,omitempty" tf:"parent_folder_arn,omitempty"`

	// Reference to a Folder in quicksight to populate parentFolderArn.
	// +kubebuilder:validation:Optional
	ParentFolderArnRef *v1.NamespacedReference `json:"parentFolderArnRef,omitempty" tf:"-"`

	// Selector for a Folder in quicksight to populate parentFolderArn.
	// +kubebuilder:validation:Optional
	ParentFolderArnSelector *v1.NamespacedSelector `json:"parentFolderArnSelector,omitempty" tf:"-"`

	// A set of resource permissions on the folder. Maximum of 64 items. See permissions.
	Permissions []FolderPermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FolderObservation struct {

	// ARN of the folder.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The time that the folder was created.
	CreatedTime *string `json:"createdTime,omitempty" tf:"created_time,omitempty"`

	// Identifier for the folder.
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// An array of ancestor ARN strings for the folder. Empty for root-level folders.
	FolderPath []*string `json:"folderPath,omitempty" tf:"folder_path,omitempty"`

	// The type of folder. By default, it is SHARED. Valid values are: SHARED.
	FolderType *string `json:"folderType,omitempty" tf:"folder_type,omitempty"`

	// A comma-delimited string joining AWS account ID and folder ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The time that the folder was last updated.
	LastUpdatedTime *string `json:"lastUpdatedTime,omitempty" tf:"last_updated_time,omitempty"`

	// Display name for the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Amazon Resource Name (ARN) for the parent folder. If not set, creates a root-level folder.
	ParentFolderArn *string `json:"parentFolderArn,omitempty" tf:"parent_folder_arn,omitempty"`

	// A set of resource permissions on the folder. Maximum of 64 items. See permissions.
	Permissions []FolderPermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type FolderParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Identifier for the folder.
	// +kubebuilder:validation:Optional
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// The type of folder. By default, it is SHARED. Valid values are: SHARED.
	// +kubebuilder:validation:Optional
	FolderType *string `json:"folderType,omitempty" tf:"folder_type,omitempty"`

	// Display name for the folder.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The Amazon Resource Name (ARN) for the parent folder. If not set, creates a root-level folder.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Folder
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	ParentFolderArn *string `json:"parentFolderArn,omitempty" tf:"parent_folder_arn,omitempty"`

	// Reference to a Folder in quicksight to populate parentFolderArn.
	// +kubebuilder:validation:Optional
	ParentFolderArnRef *v1.NamespacedReference `json:"parentFolderArnRef,omitempty" tf:"-"`

	// Selector for a Folder in quicksight to populate parentFolderArn.
	// +kubebuilder:validation:Optional
	ParentFolderArnSelector *v1.NamespacedSelector `json:"parentFolderArnSelector,omitempty" tf:"-"`

	// A set of resource permissions on the folder. Maximum of 64 items. See permissions.
	// +kubebuilder:validation:Optional
	Permissions []FolderPermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type FolderPermissionsInitParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Reference to a User in quicksight to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalRef *v1.NamespacedReference `json:"principalRef,omitempty" tf:"-"`

	// Selector for a User in quicksight to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalSelector *v1.NamespacedSelector `json:"principalSelector,omitempty" tf:"-"`
}

type FolderPermissionsObservation struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`
}

type FolderPermissionsParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("arn",true)
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`

	// Reference to a User in quicksight to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalRef *v1.NamespacedReference `json:"principalRef,omitempty" tf:"-"`

	// Selector for a User in quicksight to populate principal.
	// +kubebuilder:validation:Optional
	PrincipalSelector *v1.NamespacedSelector `json:"principalSelector,omitempty" tf:"-"`
}

// FolderSpec defines the desired state of Folder
type FolderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FolderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FolderInitParameters `json:"initProvider,omitempty"`
}

// FolderStatus defines the observed state of Folder.
type FolderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Folder is the Schema for the Folders API. Manages a QuickSight Folder.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type Folder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.folderId) || (has(self.initProvider) && has(self.initProvider.folderId))",message="spec.forProvider.folderId is a required parameter"
	Spec   FolderSpec   `json:"spec"`
	Status FolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FolderList contains a list of Folders
type FolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Folder `json:"items"`
}

// Repository type metadata.
var (
	Folder_Kind             = "Folder"
	Folder_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Folder_Kind}.String()
	Folder_KindAPIVersion   = Folder_Kind + "." + CRDGroupVersion.String()
	Folder_GroupVersionKind = CRDGroupVersion.WithKind(Folder_Kind)
)

func init() {
	SchemeBuilder.Register(&Folder{}, &FolderList{})
}
