// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by angryjet. DO NOT EDIT.
// Code transformed by upjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	common "github.com/upbound/provider-aws/v2/config/namespaced/common"
	apisresolver "github.com/upbound/provider-aws/v2/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *AccountSubscription) ResolveReferences( // ResolveReferences of this AccountSubscription.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("ds.aws.m.upbound.io", "v1beta1", "Directory", "DirectoryList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DirectoryID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.DirectoryIDRef,
			Selector:     mg.Spec.ForProvider.DirectoryIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DirectoryID")
	}
	mg.Spec.ForProvider.DirectoryID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DirectoryIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("ds.aws.m.upbound.io", "v1beta1", "Directory", "DirectoryList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DirectoryID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.DirectoryIDRef,
			Selector:     mg.Spec.InitProvider.DirectoryIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DirectoryID")
	}
	mg.Spec.InitProvider.DirectoryID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DirectoryIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Analysis.
func (mg *Analysis) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceTemplate != nil {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ThemeArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ThemeArnRef,
			Selector:     mg.Spec.ForProvider.ThemeArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ThemeArn")
	}
	mg.Spec.ForProvider.ThemeArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ThemeArnRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceTemplate != nil {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ThemeArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ThemeArnRef,
			Selector:     mg.Spec.InitProvider.ThemeArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ThemeArn")
	}
	mg.Spec.InitProvider.ThemeArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ThemeArnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Dashboard.
func (mg *Dashboard) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceTemplate != nil {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ThemeArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ThemeArnRef,
			Selector:     mg.Spec.ForProvider.ThemeArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ThemeArn")
	}
	mg.Spec.ForProvider.ThemeArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ThemeArnRef = rsp.ResolvedReference

	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceTemplate != nil {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.SourceEntity.SourceTemplate.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ThemeArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ThemeArnRef,
			Selector:     mg.Spec.InitProvider.ThemeArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ThemeArn")
	}
	mg.Spec.InitProvider.ThemeArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ThemeArnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this DataSet.
func (mg *DataSet) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ColumnLevelPermissionRules); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].Principals),
				Extract:       resource.ExtractParamPath("arn", true),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].PrincipalsRefs,
				Selector:      mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].PrincipalsSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].Principals")
		}
		mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].Principals = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.ColumnLevelPermissionRules[i3].PrincipalsRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.LogicalTableMap); i3++ {
		if mg.Spec.ForProvider.LogicalTableMap[i3].Source != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArnRef,
					Selector:     mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArn")
			}
			mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.LogicalTableMap[i3].Source.DataSetArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Permissions); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Permissions[i3].Principal),
				Extract:      resource.ExtractParamPath("arn", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Permissions[i3].PrincipalRef,
				Selector:     mg.Spec.ForProvider.Permissions[i3].PrincipalSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Permissions[i3].Principal")
		}
		mg.Spec.ForProvider.Permissions[i3].Principal = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Permissions[i3].PrincipalRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.PhysicalTableMap); i3++ {
		if mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnRef,
					Selector:     mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn")
			}
			mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.PhysicalTableMap); i3++ {
		if mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnRef,
					Selector:     mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn")
			}
			mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.PhysicalTableMap); i3++ {
		if mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArnRef,
					Selector:     mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArn")
			}
			mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.PhysicalTableMap[i3].S3Source.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.RowLevelPermissionDataSet != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RowLevelPermissionDataSet.Arn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.RowLevelPermissionDataSet.ArnRef,
				Selector:     mg.Spec.ForProvider.RowLevelPermissionDataSet.ArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.RowLevelPermissionDataSet.Arn")
		}
		mg.Spec.ForProvider.RowLevelPermissionDataSet.Arn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.RowLevelPermissionDataSet.ArnRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ColumnLevelPermissionRules); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].Principals),
				Extract:       resource.ExtractParamPath("arn", true),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].PrincipalsRefs,
				Selector:      mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].PrincipalsSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].Principals")
		}
		mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].Principals = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.ColumnLevelPermissionRules[i3].PrincipalsRefs = mrsp.ResolvedReferences

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.LogicalTableMap); i3++ {
		if mg.Spec.InitProvider.LogicalTableMap[i3].Source != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArnRef,
					Selector:     mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArn")
			}
			mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.LogicalTableMap[i3].Source.DataSetArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Permissions); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Permissions[i3].Principal),
				Extract:      resource.ExtractParamPath("arn", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Permissions[i3].PrincipalRef,
				Selector:     mg.Spec.InitProvider.Permissions[i3].PrincipalSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Permissions[i3].Principal")
		}
		mg.Spec.InitProvider.Permissions[i3].Principal = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Permissions[i3].PrincipalRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.PhysicalTableMap); i3++ {
		if mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnRef,
					Selector:     mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn")
			}
			mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.PhysicalTableMap[i3].CustomSQL.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.PhysicalTableMap); i3++ {
		if mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnRef,
					Selector:     mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn")
			}
			mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.PhysicalTableMap[i3].RelationalTable.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.PhysicalTableMap); i3++ {
		if mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArnRef,
					Selector:     mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArn")
			}
			mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.PhysicalTableMap[i3].S3Source.DataSourceArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.RowLevelPermissionDataSet != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RowLevelPermissionDataSet.Arn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.RowLevelPermissionDataSet.ArnRef,
				Selector:     mg.Spec.InitProvider.RowLevelPermissionDataSet.ArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.RowLevelPermissionDataSet.Arn")
		}
		mg.Spec.InitProvider.RowLevelPermissionDataSet.Arn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.RowLevelPermissionDataSet.ArnRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this DataSource.
func (mg *DataSource) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Credentials != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Credentials.CopySourceArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Credentials.CopySourceArnRef,
				Selector:     mg.Spec.ForProvider.Credentials.CopySourceArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Credentials.CopySourceArn")
		}
		mg.Spec.ForProvider.Credentials.CopySourceArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Credentials.CopySourceArnRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Credentials != nil {
		{
			m, l, err = apisresolver.GetManagedResource("secretsmanager.aws.m.upbound.io", "v1beta1", "Secret", "SecretList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Credentials.SecretArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Credentials.SecretArnRef,
				Selector:     mg.Spec.ForProvider.Credentials.SecretArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Credentials.SecretArn")
		}
		mg.Spec.ForProvider.Credentials.SecretArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Credentials.SecretArnRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			if mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.m.upbound.io", "v1beta1", "Bucket", "BucketList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket),
						Extract:      reference.ExternalName(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketRef,
						Selector:     mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket")
				}
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.BucketRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			if mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.m.upbound.io", "v1beta1", "Object", "ObjectList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key),
						Extract:      resource.ExtractParamPath("key", false),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeyRef,
						Selector:     mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeySelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key")
				}
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.Key = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Parameters.S3.ManifestFileLocation.KeyRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.Parameters != nil {
		if mg.Spec.ForProvider.Parameters.S3 != nil {
			{
				m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Role", "RoleList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Parameters.S3.RoleArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Parameters.S3.RoleArnRef,
					Selector:     mg.Spec.ForProvider.Parameters.S3.RoleArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Parameters.S3.RoleArn")
			}
			mg.Spec.ForProvider.Parameters.S3.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Parameters.S3.RoleArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.VPCConnectionProperties != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "VPCConnection", "VPCConnectionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArnRef,
				Selector:     mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArn")
		}
		mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.VPCConnectionProperties.VPCConnectionArnRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Credentials != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSource", "DataSourceList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Credentials.CopySourceArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Credentials.CopySourceArnRef,
				Selector:     mg.Spec.InitProvider.Credentials.CopySourceArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Credentials.CopySourceArn")
		}
		mg.Spec.InitProvider.Credentials.CopySourceArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Credentials.CopySourceArnRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Credentials != nil {
		{
			m, l, err = apisresolver.GetManagedResource("secretsmanager.aws.m.upbound.io", "v1beta1", "Secret", "SecretList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Credentials.SecretArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Credentials.SecretArnRef,
				Selector:     mg.Spec.InitProvider.Credentials.SecretArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Credentials.SecretArn")
		}
		mg.Spec.InitProvider.Credentials.SecretArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Credentials.SecretArnRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			if mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.m.upbound.io", "v1beta1", "Bucket", "BucketList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket),
						Extract:      reference.ExternalName(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketRef,
						Selector:     mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket")
				}
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Bucket = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.BucketRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			if mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation != nil {
				{
					m, l, err = apisresolver.GetManagedResource("s3.aws.m.upbound.io", "v1beta1", "Object", "ObjectList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key),
						Extract:      resource.ExtractParamPath("key", false),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeyRef,
						Selector:     mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeySelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key")
				}
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.Key = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Parameters.S3.ManifestFileLocation.KeyRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.Parameters != nil {
		if mg.Spec.InitProvider.Parameters.S3 != nil {
			{
				m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Role", "RoleList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Parameters.S3.RoleArn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Parameters.S3.RoleArnRef,
					Selector:     mg.Spec.InitProvider.Parameters.S3.RoleArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Parameters.S3.RoleArn")
			}
			mg.Spec.InitProvider.Parameters.S3.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Parameters.S3.RoleArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.VPCConnectionProperties != nil {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "VPCConnection", "VPCConnectionList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArnRef,
				Selector:     mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArn")
		}
		mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.VPCConnectionProperties.VPCConnectionArnRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Folder.
func (mg *Folder) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Folder", "FolderList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentFolderArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ParentFolderArnRef,
			Selector:     mg.Spec.ForProvider.ParentFolderArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentFolderArn")
	}
	mg.Spec.ForProvider.ParentFolderArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentFolderArnRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Permissions); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Permissions[i3].Principal),
				Extract:      resource.ExtractParamPath("arn", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Permissions[i3].PrincipalRef,
				Selector:     mg.Spec.ForProvider.Permissions[i3].PrincipalSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Permissions[i3].Principal")
		}
		mg.Spec.ForProvider.Permissions[i3].Principal = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Permissions[i3].PrincipalRef = rsp.ResolvedReference

	}
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Folder", "FolderList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentFolderArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ParentFolderArnRef,
			Selector:     mg.Spec.InitProvider.ParentFolderArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentFolderArn")
	}
	mg.Spec.InitProvider.ParentFolderArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentFolderArnRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Permissions); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Permissions[i3].Principal),
				Extract:      resource.ExtractParamPath("arn", true),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Permissions[i3].PrincipalRef,
				Selector:     mg.Spec.InitProvider.Permissions[i3].PrincipalSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Permissions[i3].Principal")
		}
		mg.Spec.InitProvider.Permissions[i3].Principal = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Permissions[i3].PrincipalRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this FolderMembership.
func (mg *FolderMembership) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Folder", "FolderList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FolderID),
			Extract:      resource.ExtractParamPath("folder_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.FolderIDRef,
			Selector:     mg.Spec.ForProvider.FolderIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FolderID")
	}
	mg.Spec.ForProvider.FolderID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FolderIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MemberID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.MemberIDRef,
			Selector:     mg.Spec.ForProvider.MemberIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemberID")
	}
	mg.Spec.ForProvider.MemberID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MemberIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Folder", "FolderList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FolderID),
			Extract:      resource.ExtractParamPath("folder_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.FolderIDRef,
			Selector:     mg.Spec.InitProvider.FolderIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FolderID")
	}
	mg.Spec.InitProvider.FolderID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FolderIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MemberID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.MemberIDRef,
			Selector:     mg.Spec.InitProvider.MemberIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MemberID")
	}
	mg.Spec.InitProvider.MemberID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MemberIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this GroupMembership.
func (mg *GroupMembership) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Group", "GroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.GroupName),
			Extract:      resource.ExtractParamPath("group_name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.GroupNameRef,
			Selector:     mg.Spec.ForProvider.GroupNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.GroupName")
	}
	mg.Spec.ForProvider.GroupName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.GroupNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Group", "GroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.GroupName),
			Extract:      resource.ExtractParamPath("group_name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.GroupNameRef,
			Selector:     mg.Spec.InitProvider.GroupNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.GroupName")
	}
	mg.Spec.InitProvider.GroupName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.GroupNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IAMPolicyAssignment.
func (mg *IAMPolicyAssignment) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Identities); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Identities[i3].User),
				Extract:       resource.ExtractParamPath("user_name", false),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.ForProvider.Identities[i3].UserRefs,
				Selector:      mg.Spec.ForProvider.Identities[i3].UserSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Identities[i3].User")
		}
		mg.Spec.ForProvider.Identities[i3].User = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Identities[i3].UserRefs = mrsp.ResolvedReferences

	}
	{
		m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Policy", "PolicyList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PolicyArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.PolicyArnRef,
			Selector:     mg.Spec.ForProvider.PolicyArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PolicyArn")
	}
	mg.Spec.ForProvider.PolicyArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PolicyArnRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Identities); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
				CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Identities[i3].User),
				Extract:       resource.ExtractParamPath("user_name", false),
				Namespace:     mg.GetNamespace(),
				References:    mg.Spec.InitProvider.Identities[i3].UserRefs,
				Selector:      mg.Spec.InitProvider.Identities[i3].UserSelector,
				To:            reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Identities[i3].User")
		}
		mg.Spec.InitProvider.Identities[i3].User = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Identities[i3].UserRefs = mrsp.ResolvedReferences

	}
	{
		m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Policy", "PolicyList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PolicyArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.PolicyArnRef,
			Selector:     mg.Spec.InitProvider.PolicyArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PolicyArn")
	}
	mg.Spec.InitProvider.PolicyArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PolicyArnRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Ingestion.
func (mg *Ingestion) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DataSetID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.DataSetIDRef,
			Selector:     mg.Spec.ForProvider.DataSetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DataSetID")
	}
	mg.Spec.ForProvider.DataSetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DataSetIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DataSetID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.DataSetIDRef,
			Selector:     mg.Spec.InitProvider.DataSetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DataSetID")
	}
	mg.Spec.InitProvider.DataSetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DataSetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this KeyRegistration.
func (mg *KeyRegistration) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.KeyRegistration); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.aws.m.upbound.io", "v1beta1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyRegistration[i3].KeyArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.KeyRegistration[i3].KeyArnRef,
				Selector:     mg.Spec.ForProvider.KeyRegistration[i3].KeyArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KeyRegistration[i3].KeyArn")
		}
		mg.Spec.ForProvider.KeyRegistration[i3].KeyArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KeyRegistration[i3].KeyArnRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KeyRegistration); i3++ {
		{
			m, l, err = apisresolver.GetManagedResource("kms.aws.m.upbound.io", "v1beta1", "Key", "KeyList")
			if err != nil {
				return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
			}
			rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyRegistration[i3].KeyArn),
				Extract:      common.ARNExtractor(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.KeyRegistration[i3].KeyArnRef,
				Selector:     mg.Spec.InitProvider.KeyRegistration[i3].KeyArnSelector,
				To:           reference.To{List: l, Managed: m},
			})
		}
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KeyRegistration[i3].KeyArn")
		}
		mg.Spec.InitProvider.KeyRegistration[i3].KeyArn = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KeyRegistration[i3].KeyArnRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this RefreshSchedule.
func (mg *RefreshSchedule) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DataSetID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.DataSetIDRef,
			Selector:     mg.Spec.ForProvider.DataSetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DataSetID")
	}
	mg.Spec.ForProvider.DataSetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DataSetIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DataSetID),
			Extract:      resource.ExtractParamPath("data_set_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.DataSetIDRef,
			Selector:     mg.Spec.InitProvider.DataSetIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DataSetID")
	}
	mg.Spec.InitProvider.DataSetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DataSetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RoleCustomPermission.
func (mg *RoleCustomPermission) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "CustomPermissions", "CustomPermissionsList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CustomPermissionsName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CustomPermissionsNameRef,
			Selector:     mg.Spec.ForProvider.CustomPermissionsNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CustomPermissionsName")
	}
	mg.Spec.ForProvider.CustomPermissionsName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CustomPermissionsNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "CustomPermissions", "CustomPermissionsList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CustomPermissionsName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CustomPermissionsNameRef,
			Selector:     mg.Spec.InitProvider.CustomPermissionsNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CustomPermissionsName")
	}
	mg.Spec.InitProvider.CustomPermissionsName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CustomPermissionsNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RoleMembership.
func (mg *RoleMembership) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Group", "GroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MemberName),
			Extract:      resource.ExtractParamPath("group_name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.MemberNameRef,
			Selector:     mg.Spec.ForProvider.MemberNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MemberName")
	}
	mg.Spec.ForProvider.MemberName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MemberNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Group", "GroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MemberName),
			Extract:      resource.ExtractParamPath("group_name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.MemberNameRef,
			Selector:     mg.Spec.InitProvider.MemberNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MemberName")
	}
	mg.Spec.InitProvider.MemberName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MemberNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Template.
func (mg *Template) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceAnalysis != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Analysis", "AnalysisList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceAnalysis.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.SourceEntity.SourceAnalysis.ArnRef,
					Selector:     mg.Spec.ForProvider.SourceEntity.SourceAnalysis.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceAnalysis.Arn")
			}
			mg.Spec.ForProvider.SourceEntity.SourceAnalysis.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SourceEntity.SourceAnalysis.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceAnalysis != nil {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.ForProvider.SourceEntity != nil {
		if mg.Spec.ForProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceAnalysis != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Analysis", "AnalysisList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceAnalysis.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.SourceEntity.SourceAnalysis.ArnRef,
					Selector:     mg.Spec.InitProvider.SourceEntity.SourceAnalysis.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceAnalysis.Arn")
			}
			mg.Spec.InitProvider.SourceEntity.SourceAnalysis.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.SourceEntity.SourceAnalysis.ArnRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceAnalysis != nil {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences); i5++ {
				{
					m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "DataSet", "DataSetList")
					if err != nil {
						return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
					}
					rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
						CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn),
						Extract:      common.ARNExtractor(),
						Namespace:    mg.GetNamespace(),
						Reference:    mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnRef,
						Selector:     mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnSelector,
						To:           reference.To{List: l, Managed: m},
					})
				}
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn")
				}
				mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArn = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.SourceEntity.SourceAnalysis.DataSetReferences[i5].DataSetArnRef = rsp.ResolvedReference

			}
		}
	}
	if mg.Spec.InitProvider.SourceEntity != nil {
		if mg.Spec.InitProvider.SourceEntity.SourceTemplate != nil {
			{
				m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
				if err != nil {
					return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
				}
				rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn),
					Extract:      common.ARNExtractor(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef,
					Selector:     mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnSelector,
					To:           reference.To{List: l, Managed: m},
				})
			}
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn")
			}
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.Arn = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.SourceEntity.SourceTemplate.ArnRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this TemplateAlias.
func (mg *TemplateAlias) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TemplateID),
			Extract:      resource.ExtractParamPath("template_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.TemplateIDRef,
			Selector:     mg.Spec.ForProvider.TemplateIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TemplateID")
	}
	mg.Spec.ForProvider.TemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TemplateIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.TemplateVersionNumber),
			Extract:      resource.ExtractParamPath("version_number", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.TemplateVersionNumberRef,
			Selector:     mg.Spec.ForProvider.TemplateVersionNumberSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TemplateVersionNumber")
	}
	mg.Spec.ForProvider.TemplateVersionNumber = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TemplateVersionNumberRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TemplateID),
			Extract:      resource.ExtractParamPath("template_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.TemplateIDRef,
			Selector:     mg.Spec.InitProvider.TemplateIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TemplateID")
	}
	mg.Spec.InitProvider.TemplateID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TemplateIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Template", "TemplateList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.TemplateVersionNumber),
			Extract:      resource.ExtractParamPath("version_number", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.TemplateVersionNumberRef,
			Selector:     mg.Spec.InitProvider.TemplateVersionNumberSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TemplateVersionNumber")
	}
	mg.Spec.InitProvider.TemplateVersionNumber = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TemplateVersionNumberRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Theme.
func (mg *Theme) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BaseThemeID),
			Extract:      resource.ExtractParamPath("theme_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.BaseThemeIDRef,
			Selector:     mg.Spec.ForProvider.BaseThemeIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BaseThemeID")
	}
	mg.Spec.ForProvider.BaseThemeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BaseThemeIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "Theme", "ThemeList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BaseThemeID),
			Extract:      resource.ExtractParamPath("theme_id", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.BaseThemeIDRef,
			Selector:     mg.Spec.InitProvider.BaseThemeIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BaseThemeID")
	}
	mg.Spec.InitProvider.BaseThemeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BaseThemeIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this UserCustomPermission.
func (mg *UserCustomPermission) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "CustomPermissions", "CustomPermissionsList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CustomPermissionsName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CustomPermissionsNameRef,
			Selector:     mg.Spec.ForProvider.CustomPermissionsNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CustomPermissionsName")
	}
	mg.Spec.ForProvider.CustomPermissionsName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CustomPermissionsNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "User", "UserList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserName),
			Extract:      resource.ExtractParamPath("user_name", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UserNameRef,
			Selector:     mg.Spec.ForProvider.UserNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserName")
	}
	mg.Spec.ForProvider.UserName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserNameRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("quicksight.aws.m.upbound.io", "v1beta1", "CustomPermissions", "CustomPermissionsList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CustomPermissionsName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CustomPermissionsNameRef,
			Selector:     mg.Spec.InitProvider.CustomPermissionsNameSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CustomPermissionsName")
	}
	mg.Spec.InitProvider.CustomPermissionsName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CustomPermissionsNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this VPCConnection.
func (mg *VPCConnection) ResolveReferences(ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Role", "RoleList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoleArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.RoleArnRef,
			Selector:     mg.Spec.ForProvider.RoleArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RoleArn")
	}
	mg.Spec.ForProvider.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RoleArnRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("ec2.aws.m.upbound.io", "v1beta1", "SecurityGroup", "SecurityGroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SecurityGroupIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.SecurityGroupIdsRefs,
			Selector:      mg.Spec.ForProvider.SecurityGroupIdsSelector,
			To:            reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecurityGroupIds")
	}
	mg.Spec.ForProvider.SecurityGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SecurityGroupIdsRefs = mrsp.ResolvedReferences
	{
		m, l, err = apisresolver.GetManagedResource("ec2.aws.m.upbound.io", "v1beta1", "Subnet", "SubnetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SubnetIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.SubnetIdsRefs,
			Selector:      mg.Spec.ForProvider.SubnetIdsSelector,
			To:            reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetIds")
	}
	mg.Spec.ForProvider.SubnetIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SubnetIdsRefs = mrsp.ResolvedReferences
	{
		m, l, err = apisresolver.GetManagedResource("iam.aws.m.upbound.io", "v1beta1", "Role", "RoleList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoleArn),
			Extract:      common.ARNExtractor(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.RoleArnRef,
			Selector:     mg.Spec.InitProvider.RoleArnSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RoleArn")
	}
	mg.Spec.InitProvider.RoleArn = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RoleArnRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("ec2.aws.m.upbound.io", "v1beta1", "SecurityGroup", "SecurityGroupList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.SecurityGroupIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.SecurityGroupIdsRefs,
			Selector:      mg.Spec.InitProvider.SecurityGroupIdsSelector,
			To:            reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SecurityGroupIds")
	}
	mg.Spec.InitProvider.SecurityGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SecurityGroupIdsRefs = mrsp.ResolvedReferences
	{
		m, l, err = apisresolver.GetManagedResource("ec2.aws.m.upbound.io", "v1beta1", "Subnet", "SubnetList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.SubnetIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.SubnetIdsRefs,
			Selector:      mg.Spec.InitProvider.SubnetIdsSelector,
			To:            reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetIds")
	}
	mg.Spec.InitProvider.SubnetIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SubnetIdsRefs = mrsp.ResolvedReferences

	return nil
}
