// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IngestionInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// ID of the dataset used in the ingestion.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDRef *v1.NamespacedReference `json:"dataSetIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDSelector *v1.NamespacedSelector `json:"dataSetIdSelector,omitempty" tf:"-"`

	// Type of ingestion to be created. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	IngestionType *string `json:"ingestionType,omitempty" tf:"ingestion_type,omitempty"`
}

type IngestionObservation struct {

	// ARN of the Ingestion.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// ID of the dataset used in the ingestion.
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// A comma-delimited string joining AWS account ID, data set ID, and ingestion ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Ingestion status.
	IngestionStatus *string `json:"ingestionStatus,omitempty" tf:"ingestion_status,omitempty"`

	// Type of ingestion to be created. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	IngestionType *string `json:"ingestionType,omitempty" tf:"ingestion_type,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IngestionParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// ID of the dataset used in the ingestion.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.DataSet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("data_set_id",false)
	// +kubebuilder:validation:Optional
	DataSetID *string `json:"dataSetId,omitempty" tf:"data_set_id,omitempty"`

	// Reference to a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDRef *v1.NamespacedReference `json:"dataSetIdRef,omitempty" tf:"-"`

	// Selector for a DataSet in quicksight to populate dataSetId.
	// +kubebuilder:validation:Optional
	DataSetIDSelector *v1.NamespacedSelector `json:"dataSetIdSelector,omitempty" tf:"-"`

	// Type of ingestion to be created. Valid values are INCREMENTAL_REFRESH and FULL_REFRESH.
	// +kubebuilder:validation:Optional
	IngestionType *string `json:"ingestionType,omitempty" tf:"ingestion_type,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

// IngestionSpec defines the desired state of Ingestion
type IngestionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IngestionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IngestionInitParameters `json:"initProvider,omitempty"`
}

// IngestionStatus defines the observed state of Ingestion.
type IngestionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IngestionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Ingestion is the Schema for the Ingestions API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type Ingestion struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ingestionType) || (has(self.initProvider) && has(self.initProvider.ingestionType))",message="spec.forProvider.ingestionType is a required parameter"
	Spec   IngestionSpec   `json:"spec"`
	Status IngestionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IngestionList contains a list of Ingestions
type IngestionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Ingestion `json:"items"`
}

// Repository type metadata.
var (
	Ingestion_Kind             = "Ingestion"
	Ingestion_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Ingestion_Kind}.String()
	Ingestion_KindAPIVersion   = Ingestion_Kind + "." + CRDGroupVersion.String()
	Ingestion_GroupVersionKind = CRDGroupVersion.WithKind(Ingestion_Kind)
)

func init() {
	SchemeBuilder.Register(&Ingestion{}, &IngestionList{})
}
