// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IAMPolicyAssignmentInitParameters struct {

	// Status of the assignment. Valid values are ENABLED, DISABLED, and DRAFT.
	AssignmentStatus *string `json:"assignmentStatus,omitempty" tf:"assignment_status,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Amazon QuickSight users, groups, or both to assign the policy to. See identities block.
	Identities []IdentitiesInitParameters `json:"identities,omitempty" tf:"identities,omitempty"`

	// Namespace that contains the assignment. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ARN of the IAM policy to apply to the Amazon QuickSight users and groups specified in this assignment.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/iam/v1beta1.Policy
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	PolicyArn *string `json:"policyArn,omitempty" tf:"policy_arn,omitempty"`

	// Reference to a Policy in iam to populate policyArn.
	// +kubebuilder:validation:Optional
	PolicyArnRef *v1.NamespacedReference `json:"policyArnRef,omitempty" tf:"-"`

	// Selector for a Policy in iam to populate policyArn.
	// +kubebuilder:validation:Optional
	PolicyArnSelector *v1.NamespacedSelector `json:"policyArnSelector,omitempty" tf:"-"`
}

type IAMPolicyAssignmentObservation struct {

	// Assignment ID.
	AssignmentID *string `json:"assignmentId,omitempty" tf:"assignment_id,omitempty"`

	// Status of the assignment. Valid values are ENABLED, DISABLED, and DRAFT.
	AssignmentStatus *string `json:"assignmentStatus,omitempty" tf:"assignment_status,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// A comma-delimited string joining AWS account ID, namespace, and assignment name.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Amazon QuickSight users, groups, or both to assign the policy to. See identities block.
	Identities []IdentitiesObservation `json:"identities,omitempty" tf:"identities,omitempty"`

	// Namespace that contains the assignment. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ARN of the IAM policy to apply to the Amazon QuickSight users and groups specified in this assignment.
	PolicyArn *string `json:"policyArn,omitempty" tf:"policy_arn,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IAMPolicyAssignmentParameters struct {

	// Status of the assignment. Valid values are ENABLED, DISABLED, and DRAFT.
	// +kubebuilder:validation:Optional
	AssignmentStatus *string `json:"assignmentStatus,omitempty" tf:"assignment_status,omitempty"`

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Amazon QuickSight users, groups, or both to assign the policy to. See identities block.
	// +kubebuilder:validation:Optional
	Identities []IdentitiesParameters `json:"identities,omitempty" tf:"identities,omitempty"`

	// Namespace that contains the assignment. Defaults to default.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// ARN of the IAM policy to apply to the Amazon QuickSight users and groups specified in this assignment.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/iam/v1beta1.Policy
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	PolicyArn *string `json:"policyArn,omitempty" tf:"policy_arn,omitempty"`

	// Reference to a Policy in iam to populate policyArn.
	// +kubebuilder:validation:Optional
	PolicyArnRef *v1.NamespacedReference `json:"policyArnRef,omitempty" tf:"-"`

	// Selector for a Policy in iam to populate policyArn.
	// +kubebuilder:validation:Optional
	PolicyArnSelector *v1.NamespacedSelector `json:"policyArnSelector,omitempty" tf:"-"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

type IdentitiesInitParameters struct {

	// Array of Quicksight group names to assign the policy to.
	// +listType=set
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// Array of Quicksight user names to assign the policy to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("user_name",false)
	// +listType=set
	User []*string `json:"user,omitempty" tf:"user,omitempty"`

	// References to User in quicksight to populate user.
	// +kubebuilder:validation:Optional
	UserRefs []v1.NamespacedReference `json:"userRefs,omitempty" tf:"-"`

	// Selector for a list of User in quicksight to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v1.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

type IdentitiesObservation struct {

	// Array of Quicksight group names to assign the policy to.
	// +listType=set
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// Array of Quicksight user names to assign the policy to.
	// +listType=set
	User []*string `json:"user,omitempty" tf:"user,omitempty"`
}

type IdentitiesParameters struct {

	// Array of Quicksight group names to assign the policy to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Group []*string `json:"group,omitempty" tf:"group,omitempty"`

	// Array of Quicksight user names to assign the policy to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.User
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("user_name",false)
	// +kubebuilder:validation:Optional
	// +listType=set
	User []*string `json:"user,omitempty" tf:"user,omitempty"`

	// References to User in quicksight to populate user.
	// +kubebuilder:validation:Optional
	UserRefs []v1.NamespacedReference `json:"userRefs,omitempty" tf:"-"`

	// Selector for a list of User in quicksight to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v1.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

// IAMPolicyAssignmentSpec defines the desired state of IAMPolicyAssignment
type IAMPolicyAssignmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IAMPolicyAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IAMPolicyAssignmentInitParameters `json:"initProvider,omitempty"`
}

// IAMPolicyAssignmentStatus defines the observed state of IAMPolicyAssignment.
type IAMPolicyAssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IAMPolicyAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IAMPolicyAssignment is the Schema for the IAMPolicyAssignments API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type IAMPolicyAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.assignmentStatus) || (has(self.initProvider) && has(self.initProvider.assignmentStatus))",message="spec.forProvider.assignmentStatus is a required parameter"
	Spec   IAMPolicyAssignmentSpec   `json:"spec"`
	Status IAMPolicyAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IAMPolicyAssignmentList contains a list of IAMPolicyAssignments
type IAMPolicyAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IAMPolicyAssignment `json:"items"`
}

// Repository type metadata.
var (
	IAMPolicyAssignment_Kind             = "IAMPolicyAssignment"
	IAMPolicyAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IAMPolicyAssignment_Kind}.String()
	IAMPolicyAssignment_KindAPIVersion   = IAMPolicyAssignment_Kind + "." + CRDGroupVersion.String()
	IAMPolicyAssignment_GroupVersionKind = CRDGroupVersion.WithKind(IAMPolicyAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&IAMPolicyAssignment{}, &IAMPolicyAssignmentList{})
}
