// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type IPRestrictionInitParameters struct {

	// Whether IP rules are turned on.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Map of allowed IPv4 CIDR ranges and descriptions.
	// +mapType=granular
	IPRestrictionRuleMap map[string]*string `json:"ipRestrictionRuleMap,omitempty" tf:"ip_restriction_rule_map,omitempty"`

	// Map of allowed VPC endpoint IDs and descriptions.
	// +mapType=granular
	VPCEndpointIDRestrictionRuleMap map[string]*string `json:"vpcEndpointIdRestrictionRuleMap,omitempty" tf:"vpc_endpoint_id_restriction_rule_map,omitempty"`

	// Map of VPC IDs and descriptions. Traffic from all VPC endpoints that are present in the specified VPC is allowed.
	// +mapType=granular
	VPCIDRestrictionRuleMap map[string]*string `json:"vpcIdRestrictionRuleMap,omitempty" tf:"vpc_id_restriction_rule_map,omitempty"`
}

type IPRestrictionObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Whether IP rules are turned on.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Map of allowed IPv4 CIDR ranges and descriptions.
	// +mapType=granular
	IPRestrictionRuleMap map[string]*string `json:"ipRestrictionRuleMap,omitempty" tf:"ip_restriction_rule_map,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Map of allowed VPC endpoint IDs and descriptions.
	// +mapType=granular
	VPCEndpointIDRestrictionRuleMap map[string]*string `json:"vpcEndpointIdRestrictionRuleMap,omitempty" tf:"vpc_endpoint_id_restriction_rule_map,omitempty"`

	// Map of VPC IDs and descriptions. Traffic from all VPC endpoints that are present in the specified VPC is allowed.
	// +mapType=granular
	VPCIDRestrictionRuleMap map[string]*string `json:"vpcIdRestrictionRuleMap,omitempty" tf:"vpc_id_restriction_rule_map,omitempty"`
}

type IPRestrictionParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Whether IP rules are turned on.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Map of allowed IPv4 CIDR ranges and descriptions.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	IPRestrictionRuleMap map[string]*string `json:"ipRestrictionRuleMap,omitempty" tf:"ip_restriction_rule_map,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Map of allowed VPC endpoint IDs and descriptions.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VPCEndpointIDRestrictionRuleMap map[string]*string `json:"vpcEndpointIdRestrictionRuleMap,omitempty" tf:"vpc_endpoint_id_restriction_rule_map,omitempty"`

	// Map of VPC IDs and descriptions. Traffic from all VPC endpoints that are present in the specified VPC is allowed.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	VPCIDRestrictionRuleMap map[string]*string `json:"vpcIdRestrictionRuleMap,omitempty" tf:"vpc_id_restriction_rule_map,omitempty"`
}

// IPRestrictionSpec defines the desired state of IPRestriction
type IPRestrictionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            IPRestrictionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IPRestrictionInitParameters `json:"initProvider,omitempty"`
}

// IPRestrictionStatus defines the observed state of IPRestriction.
type IPRestrictionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IPRestrictionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IPRestriction is the Schema for the IPRestrictions API. Manages the content and status of IP rules.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type IPRestriction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.enabled) || (has(self.initProvider) && has(self.initProvider.enabled))",message="spec.forProvider.enabled is a required parameter"
	Spec   IPRestrictionSpec   `json:"spec"`
	Status IPRestrictionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IPRestrictionList contains a list of IPRestrictions
type IPRestrictionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPRestriction `json:"items"`
}

// Repository type metadata.
var (
	IPRestriction_Kind             = "IPRestriction"
	IPRestriction_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IPRestriction_Kind}.String()
	IPRestriction_KindAPIVersion   = IPRestriction_Kind + "." + CRDGroupVersion.String()
	IPRestriction_GroupVersionKind = CRDGroupVersion.WithKind(IPRestriction_Kind)
)

func init() {
	SchemeBuilder.Register(&IPRestriction{}, &IPRestrictionList{})
}
