// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type KeyRegistrationInitParameters struct {

	// Registered keys. See key_registration.
	KeyRegistration []KeyRegistrationKeyRegistrationInitParameters `json:"keyRegistration,omitempty" tf:"key_registration,omitempty"`
}

type KeyRegistrationKeyRegistrationInitParameters struct {

	// Whether the key is set as the default key for encryption and decryption use.
	DefaultKey *bool `json:"defaultKey,omitempty" tf:"default_key,omitempty"`

	// ARN of the AWS KMS key that is registered for encryption and decryption use.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/kms/v1beta1.Key
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	KeyArn *string `json:"keyArn,omitempty" tf:"key_arn,omitempty"`

	// Reference to a Key in kms to populate keyArn.
	// +kubebuilder:validation:Optional
	KeyArnRef *v1.NamespacedReference `json:"keyArnRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate keyArn.
	// +kubebuilder:validation:Optional
	KeyArnSelector *v1.NamespacedSelector `json:"keyArnSelector,omitempty" tf:"-"`
}

type KeyRegistrationKeyRegistrationObservation struct {

	// Whether the key is set as the default key for encryption and decryption use.
	DefaultKey *bool `json:"defaultKey,omitempty" tf:"default_key,omitempty"`

	// ARN of the AWS KMS key that is registered for encryption and decryption use.
	KeyArn *string `json:"keyArn,omitempty" tf:"key_arn,omitempty"`
}

type KeyRegistrationKeyRegistrationParameters struct {

	// Whether the key is set as the default key for encryption and decryption use.
	// +kubebuilder:validation:Optional
	DefaultKey *bool `json:"defaultKey,omitempty" tf:"default_key,omitempty"`

	// ARN of the AWS KMS key that is registered for encryption and decryption use.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/kms/v1beta1.Key
	// +crossplane:generate:reference:extractor=github.com/upbound/provider-aws/v2/config/namespaced/common.ARNExtractor()
	// +kubebuilder:validation:Optional
	KeyArn *string `json:"keyArn,omitempty" tf:"key_arn,omitempty"`

	// Reference to a Key in kms to populate keyArn.
	// +kubebuilder:validation:Optional
	KeyArnRef *v1.NamespacedReference `json:"keyArnRef,omitempty" tf:"-"`

	// Selector for a Key in kms to populate keyArn.
	// +kubebuilder:validation:Optional
	KeyArnSelector *v1.NamespacedSelector `json:"keyArnSelector,omitempty" tf:"-"`
}

type KeyRegistrationObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Registered keys. See key_registration.
	KeyRegistration []KeyRegistrationKeyRegistrationObservation `json:"keyRegistration,omitempty" tf:"key_registration,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type KeyRegistrationParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Registered keys. See key_registration.
	// +kubebuilder:validation:Optional
	KeyRegistration []KeyRegistrationKeyRegistrationParameters `json:"keyRegistration,omitempty" tf:"key_registration,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`
}

// KeyRegistrationSpec defines the desired state of KeyRegistration
type KeyRegistrationSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            KeyRegistrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyRegistrationInitParameters `json:"initProvider,omitempty"`
}

// KeyRegistrationStatus defines the observed state of KeyRegistration.
type KeyRegistrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyRegistrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KeyRegistration is the Schema for the KeyRegistrations API. Registers customer managed keys in a Amazon QuickSight account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type KeyRegistration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KeyRegistrationSpec   `json:"spec"`
	Status            KeyRegistrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyRegistrationList contains a list of KeyRegistrations
type KeyRegistrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeyRegistration `json:"items"`
}

// Repository type metadata.
var (
	KeyRegistration_Kind             = "KeyRegistration"
	KeyRegistration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KeyRegistration_Kind}.String()
	KeyRegistration_KindAPIVersion   = KeyRegistration_Kind + "." + CRDGroupVersion.String()
	KeyRegistration_GroupVersionKind = CRDGroupVersion.WithKind(KeyRegistration_Kind)
)

func init() {
	SchemeBuilder.Register(&KeyRegistration{}, &KeyRegistrationList{})
}
