// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type QuicksightNamespaceInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// User identity directory type. Defaults to QUICKSIGHT, the only current valid value.
	IdentityStore *string `json:"identityStore,omitempty" tf:"identity_store,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

type QuicksightNamespaceObservation struct {

	// ARN of the Namespace.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Namespace AWS Region.
	CapacityRegion *string `json:"capacityRegion,omitempty" tf:"capacity_region,omitempty"`

	// Creation status of the namespace.
	CreationStatus *string `json:"creationStatus,omitempty" tf:"creation_status,omitempty"`

	// A comma-delimited string joining AWS account ID and namespace.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// User identity directory type. Defaults to QUICKSIGHT, the only current valid value.
	IdentityStore *string `json:"identityStore,omitempty" tf:"identity_store,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`
}

type QuicksightNamespaceParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// User identity directory type. Defaults to QUICKSIGHT, the only current valid value.
	// +kubebuilder:validation:Optional
	IdentityStore *string `json:"identityStore,omitempty" tf:"identity_store,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`
}

// QuicksightNamespaceSpec defines the desired state of QuicksightNamespace
type QuicksightNamespaceSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            QuicksightNamespaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider QuicksightNamespaceInitParameters `json:"initProvider,omitempty"`
}

// QuicksightNamespaceStatus defines the observed state of QuicksightNamespace.
type QuicksightNamespaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        QuicksightNamespaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// QuicksightNamespace is the Schema for the QuicksightNamespaces API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type QuicksightNamespace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              QuicksightNamespaceSpec   `json:"spec"`
	Status            QuicksightNamespaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// QuicksightNamespaceList contains a list of QuicksightNamespaces
type QuicksightNamespaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []QuicksightNamespace `json:"items"`
}

// Repository type metadata.
var (
	QuicksightNamespace_Kind             = "QuicksightNamespace"
	QuicksightNamespace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: QuicksightNamespace_Kind}.String()
	QuicksightNamespace_KindAPIVersion   = QuicksightNamespace_Kind + "." + CRDGroupVersion.String()
	QuicksightNamespace_GroupVersionKind = CRDGroupVersion.WithKind(QuicksightNamespace_Kind)
)

func init() {
	SchemeBuilder.Register(&QuicksightNamespace{}, &QuicksightNamespaceList{})
}
