// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RoleMembershipInitParameters struct {

	// Name of the group to be added to the role.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("group_name",false)
	MemberName *string `json:"memberName,omitempty" tf:"member_name,omitempty"`

	// Reference to a Group in quicksight to populate memberName.
	// +kubebuilder:validation:Optional
	MemberNameRef *v1.NamespacedReference `json:"memberNameRef,omitempty" tf:"-"`

	// Selector for a Group in quicksight to populate memberName.
	// +kubebuilder:validation:Optional
	MemberNameSelector *v1.NamespacedSelector `json:"memberNameSelector,omitempty" tf:"-"`
}

type RoleMembershipObservation struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the group to be added to the role.
	MemberName *string `json:"memberName,omitempty" tf:"member_name,omitempty"`

	// Name of the namespace. Defaults to default.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Role to add the group to. Valid values are ADMIN, AUTHOR, READER, ADMIN_PRO, AUTHOR_PRO, and READER_PRO.
	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RoleMembershipParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// Name of the group to be added to the role.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Group
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("group_name",false)
	// +kubebuilder:validation:Optional
	MemberName *string `json:"memberName,omitempty" tf:"member_name,omitempty"`

	// Reference to a Group in quicksight to populate memberName.
	// +kubebuilder:validation:Optional
	MemberNameRef *v1.NamespacedReference `json:"memberNameRef,omitempty" tf:"-"`

	// Selector for a Group in quicksight to populate memberName.
	// +kubebuilder:validation:Optional
	MemberNameSelector *v1.NamespacedSelector `json:"memberNameSelector,omitempty" tf:"-"`

	// Name of the namespace. Defaults to default.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Role to add the group to. Valid values are ADMIN, AUTHOR, READER, ADMIN_PRO, AUTHOR_PRO, and READER_PRO.
	// +kubebuilder:validation:Required
	Role *string `json:"role" tf:"role,omitempty"`
}

// RoleMembershipSpec defines the desired state of RoleMembership
type RoleMembershipSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RoleMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RoleMembershipInitParameters `json:"initProvider,omitempty"`
}

// RoleMembershipStatus defines the observed state of RoleMembership.
type RoleMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RoleMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RoleMembership is the Schema for the RoleMemberships API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type RoleMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              RoleMembershipSpec   `json:"spec"`
	Status            RoleMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RoleMembershipList contains a list of RoleMemberships
type RoleMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RoleMembership `json:"items"`
}

// Repository type metadata.
var (
	RoleMembership_Kind             = "RoleMembership"
	RoleMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RoleMembership_Kind}.String()
	RoleMembership_KindAPIVersion   = RoleMembership_Kind + "." + CRDGroupVersion.String()
	RoleMembership_GroupVersionKind = CRDGroupVersion.WithKind(RoleMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&RoleMembership{}, &RoleMembershipList{})
}
