// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BorderInitParameters struct {

	// The option to enable display of borders for visuals.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type BorderObservation struct {

	// The option to enable display of borders for visuals.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type BorderParameters struct {

	// The option to enable display of borders for visuals.
	// +kubebuilder:validation:Optional
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type ConfigurationInitParameters struct {

	// Color properties that apply to chart data colors. See data_color_palette.
	DataColorPalette *DataColorPaletteInitParameters `json:"dataColorPalette,omitempty" tf:"data_color_palette,omitempty"`

	// Display options related to sheets. See sheet.
	Sheet *SheetInitParameters `json:"sheet,omitempty" tf:"sheet,omitempty"`

	// Determines the typography options. See typography.
	Typography *TypographyInitParameters `json:"typography,omitempty" tf:"typography,omitempty"`

	// Color properties that apply to the UI and to charts, excluding the colors that apply to data. See ui_color_palette.
	UIColorPalette *UIColorPaletteInitParameters `json:"uiColorPalette,omitempty" tf:"ui_color_palette,omitempty"`
}

type ConfigurationObservation struct {

	// Color properties that apply to chart data colors. See data_color_palette.
	DataColorPalette *DataColorPaletteObservation `json:"dataColorPalette,omitempty" tf:"data_color_palette,omitempty"`

	// Display options related to sheets. See sheet.
	Sheet *SheetObservation `json:"sheet,omitempty" tf:"sheet,omitempty"`

	// Determines the typography options. See typography.
	Typography *TypographyObservation `json:"typography,omitempty" tf:"typography,omitempty"`

	// Color properties that apply to the UI and to charts, excluding the colors that apply to data. See ui_color_palette.
	UIColorPalette *UIColorPaletteObservation `json:"uiColorPalette,omitempty" tf:"ui_color_palette,omitempty"`
}

type ConfigurationParameters struct {

	// Color properties that apply to chart data colors. See data_color_palette.
	// +kubebuilder:validation:Optional
	DataColorPalette *DataColorPaletteParameters `json:"dataColorPalette,omitempty" tf:"data_color_palette,omitempty"`

	// Display options related to sheets. See sheet.
	// +kubebuilder:validation:Optional
	Sheet *SheetParameters `json:"sheet,omitempty" tf:"sheet,omitempty"`

	// Determines the typography options. See typography.
	// +kubebuilder:validation:Optional
	Typography *TypographyParameters `json:"typography,omitempty" tf:"typography,omitempty"`

	// Color properties that apply to the UI and to charts, excluding the colors that apply to data. See ui_color_palette.
	// +kubebuilder:validation:Optional
	UIColorPalette *UIColorPaletteParameters `json:"uiColorPalette,omitempty" tf:"ui_color_palette,omitempty"`
}

type DataColorPaletteInitParameters struct {

	// List of hexadecimal codes for the colors. Minimum of 8 items and maximum of 20 items.
	Colors []*string `json:"colors,omitempty" tf:"colors,omitempty"`

	// The hexadecimal code of a color that applies to charts where a lack of data is highlighted.
	EmptyFillColor *string `json:"emptyFillColor,omitempty" tf:"empty_fill_color,omitempty"`

	// The minimum and maximum hexadecimal codes that describe a color gradient. List of exactly 2 items.
	MinMaxGradient []*string `json:"minMaxGradient,omitempty" tf:"min_max_gradient,omitempty"`
}

type DataColorPaletteObservation struct {

	// List of hexadecimal codes for the colors. Minimum of 8 items and maximum of 20 items.
	Colors []*string `json:"colors,omitempty" tf:"colors,omitempty"`

	// The hexadecimal code of a color that applies to charts where a lack of data is highlighted.
	EmptyFillColor *string `json:"emptyFillColor,omitempty" tf:"empty_fill_color,omitempty"`

	// The minimum and maximum hexadecimal codes that describe a color gradient. List of exactly 2 items.
	MinMaxGradient []*string `json:"minMaxGradient,omitempty" tf:"min_max_gradient,omitempty"`
}

type DataColorPaletteParameters struct {

	// List of hexadecimal codes for the colors. Minimum of 8 items and maximum of 20 items.
	// +kubebuilder:validation:Optional
	Colors []*string `json:"colors,omitempty" tf:"colors,omitempty"`

	// The hexadecimal code of a color that applies to charts where a lack of data is highlighted.
	// +kubebuilder:validation:Optional
	EmptyFillColor *string `json:"emptyFillColor,omitempty" tf:"empty_fill_color,omitempty"`

	// The minimum and maximum hexadecimal codes that describe a color gradient. List of exactly 2 items.
	// +kubebuilder:validation:Optional
	MinMaxGradient []*string `json:"minMaxGradient,omitempty" tf:"min_max_gradient,omitempty"`
}

type FontFamiliesInitParameters struct {

	// Font family name.
	FontFamily *string `json:"fontFamily,omitempty" tf:"font_family,omitempty"`
}

type FontFamiliesObservation struct {

	// Font family name.
	FontFamily *string `json:"fontFamily,omitempty" tf:"font_family,omitempty"`
}

type FontFamiliesParameters struct {

	// Font family name.
	// +kubebuilder:validation:Optional
	FontFamily *string `json:"fontFamily,omitempty" tf:"font_family,omitempty"`
}

type GutterInitParameters struct {

	// This Boolean value controls whether to display a gutter space between sheet tiles.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type GutterObservation struct {

	// This Boolean value controls whether to display a gutter space between sheet tiles.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type GutterParameters struct {

	// This Boolean value controls whether to display a gutter space between sheet tiles.
	// +kubebuilder:validation:Optional
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type MarginInitParameters struct {

	// This Boolean value controls whether to display sheet margins.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type MarginObservation struct {

	// This Boolean value controls whether to display sheet margins.
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type MarginParameters struct {

	// This Boolean value controls whether to display sheet margins.
	// +kubebuilder:validation:Optional
	Show *bool `json:"show,omitempty" tf:"show,omitempty"`
}

type SheetInitParameters struct {

	// The display options for tiles. See tile.
	Tile *TileInitParameters `json:"tile,omitempty" tf:"tile,omitempty"`

	// The layout options for tiles. See tile_layout.
	TileLayout *TileLayoutInitParameters `json:"tileLayout,omitempty" tf:"tile_layout,omitempty"`
}

type SheetObservation struct {

	// The display options for tiles. See tile.
	Tile *TileObservation `json:"tile,omitempty" tf:"tile,omitempty"`

	// The layout options for tiles. See tile_layout.
	TileLayout *TileLayoutObservation `json:"tileLayout,omitempty" tf:"tile_layout,omitempty"`
}

type SheetParameters struct {

	// The display options for tiles. See tile.
	// +kubebuilder:validation:Optional
	Tile *TileParameters `json:"tile,omitempty" tf:"tile,omitempty"`

	// The layout options for tiles. See tile_layout.
	// +kubebuilder:validation:Optional
	TileLayout *TileLayoutParameters `json:"tileLayout,omitempty" tf:"tile_layout,omitempty"`
}

type ThemeInitParameters struct {

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the theme that a custom theme will inherit from. All themes inherit from one of the starting themes defined by Amazon QuickSight. For a list of the starting themes, use ListThemes or choose Themes from within an analysis.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Theme
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("theme_id",false)
	BaseThemeID *string `json:"baseThemeId,omitempty" tf:"base_theme_id,omitempty"`

	// Reference to a Theme in quicksight to populate baseThemeId.
	// +kubebuilder:validation:Optional
	BaseThemeIDRef *v1.NamespacedReference `json:"baseThemeIdRef,omitempty" tf:"-"`

	// Selector for a Theme in quicksight to populate baseThemeId.
	// +kubebuilder:validation:Optional
	BaseThemeIDSelector *v1.NamespacedSelector `json:"baseThemeIdSelector,omitempty" tf:"-"`

	// The theme configuration, which contains the theme display properties. See configuration.
	Configuration *ConfigurationInitParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// Display name of the theme.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the theme. Maximum of 64 items. See permissions.
	Permissions []ThemePermissionsInitParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Identifier of the theme.
	ThemeID *string `json:"themeId,omitempty" tf:"theme_id,omitempty"`

	// A description of the current theme version being created/updated.
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`
}

type ThemeObservation struct {

	// ARN of the theme.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// AWS account ID.
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the theme that a custom theme will inherit from. All themes inherit from one of the starting themes defined by Amazon QuickSight. For a list of the starting themes, use ListThemes or choose Themes from within an analysis.
	BaseThemeID *string `json:"baseThemeId,omitempty" tf:"base_theme_id,omitempty"`

	// The theme configuration, which contains the theme display properties. See configuration.
	Configuration *ConfigurationObservation `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// The time that the theme was created.
	CreatedTime *string `json:"createdTime,omitempty" tf:"created_time,omitempty"`

	// A comma-delimited string joining AWS account ID and theme ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The time that the theme was last updated.
	LastUpdatedTime *string `json:"lastUpdatedTime,omitempty" tf:"last_updated_time,omitempty"`

	// Display name of the theme.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the theme. Maximum of 64 items. See permissions.
	Permissions []ThemePermissionsObservation `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The theme creation status.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Key-value map of resource tags.
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	// +mapType=granular
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// Identifier of the theme.
	ThemeID *string `json:"themeId,omitempty" tf:"theme_id,omitempty"`

	// A description of the current theme version being created/updated.
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`

	// The version number of the theme version.
	VersionNumber *float64 `json:"versionNumber,omitempty" tf:"version_number,omitempty"`
}

type ThemeParameters struct {

	// AWS account ID.
	// +kubebuilder:validation:Optional
	AwsAccountID *string `json:"awsAccountId,omitempty" tf:"aws_account_id,omitempty"`

	// The ID of the theme that a custom theme will inherit from. All themes inherit from one of the starting themes defined by Amazon QuickSight. For a list of the starting themes, use ListThemes or choose Themes from within an analysis.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/v2/apis/namespaced/quicksight/v1beta1.Theme
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("theme_id",false)
	// +kubebuilder:validation:Optional
	BaseThemeID *string `json:"baseThemeId,omitempty" tf:"base_theme_id,omitempty"`

	// Reference to a Theme in quicksight to populate baseThemeId.
	// +kubebuilder:validation:Optional
	BaseThemeIDRef *v1.NamespacedReference `json:"baseThemeIdRef,omitempty" tf:"-"`

	// Selector for a Theme in quicksight to populate baseThemeId.
	// +kubebuilder:validation:Optional
	BaseThemeIDSelector *v1.NamespacedSelector `json:"baseThemeIdSelector,omitempty" tf:"-"`

	// The theme configuration, which contains the theme display properties. See configuration.
	// +kubebuilder:validation:Optional
	Configuration *ConfigurationParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// Display name of the theme.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of resource permissions on the theme. Maximum of 64 items. See permissions.
	// +kubebuilder:validation:Optional
	Permissions []ThemePermissionsParameters `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// Region where this resource will be managed. Defaults to the Region set in the provider configuration.
	// Region is the region you'd like your resource to be created in.
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"region,omitempty"`

	// Key-value map of resource tags.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Identifier of the theme.
	// +kubebuilder:validation:Optional
	ThemeID *string `json:"themeId,omitempty" tf:"theme_id,omitempty"`

	// A description of the current theme version being created/updated.
	// +kubebuilder:validation:Optional
	VersionDescription *string `json:"versionDescription,omitempty" tf:"version_description,omitempty"`
}

type ThemePermissionsInitParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`
}

type ThemePermissionsObservation struct {

	// List of IAM actions to grant or revoke permissions on.
	// +listType=set
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	Principal *string `json:"principal,omitempty" tf:"principal,omitempty"`
}

type ThemePermissionsParameters struct {

	// List of IAM actions to grant or revoke permissions on.
	// +kubebuilder:validation:Optional
	// +listType=set
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// ARN of the principal. See the ResourcePermission documentation for the applicable ARN values.
	// +kubebuilder:validation:Optional
	Principal *string `json:"principal" tf:"principal,omitempty"`
}

type TileInitParameters struct {

	// The border around a tile. See border.
	Border *BorderInitParameters `json:"border,omitempty" tf:"border,omitempty"`
}

type TileLayoutInitParameters struct {

	// The gutter settings that apply between tiles. See gutter.
	Gutter *GutterInitParameters `json:"gutter,omitempty" tf:"gutter,omitempty"`

	// The margin settings that apply around the outside edge of sheets. See margin.
	Margin *MarginInitParameters `json:"margin,omitempty" tf:"margin,omitempty"`
}

type TileLayoutObservation struct {

	// The gutter settings that apply between tiles. See gutter.
	Gutter *GutterObservation `json:"gutter,omitempty" tf:"gutter,omitempty"`

	// The margin settings that apply around the outside edge of sheets. See margin.
	Margin *MarginObservation `json:"margin,omitempty" tf:"margin,omitempty"`
}

type TileLayoutParameters struct {

	// The gutter settings that apply between tiles. See gutter.
	// +kubebuilder:validation:Optional
	Gutter *GutterParameters `json:"gutter,omitempty" tf:"gutter,omitempty"`

	// The margin settings that apply around the outside edge of sheets. See margin.
	// +kubebuilder:validation:Optional
	Margin *MarginParameters `json:"margin,omitempty" tf:"margin,omitempty"`
}

type TileObservation struct {

	// The border around a tile. See border.
	Border *BorderObservation `json:"border,omitempty" tf:"border,omitempty"`
}

type TileParameters struct {

	// The border around a tile. See border.
	// +kubebuilder:validation:Optional
	Border *BorderParameters `json:"border,omitempty" tf:"border,omitempty"`
}

type TypographyInitParameters struct {

	// Determines the list of font families. Maximum number of 5 items. See font_families.
	FontFamilies []FontFamiliesInitParameters `json:"fontFamilies,omitempty" tf:"font_families,omitempty"`
}

type TypographyObservation struct {

	// Determines the list of font families. Maximum number of 5 items. See font_families.
	FontFamilies []FontFamiliesObservation `json:"fontFamilies,omitempty" tf:"font_families,omitempty"`
}

type TypographyParameters struct {

	// Determines the list of font families. Maximum number of 5 items. See font_families.
	// +kubebuilder:validation:Optional
	FontFamilies []FontFamiliesParameters `json:"fontFamilies,omitempty" tf:"font_families,omitempty"`
}

type UIColorPaletteInitParameters struct {

	// Color (hexadecimal) that applies to selected states and buttons.
	Accent *string `json:"accent,omitempty" tf:"accent,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the accent color.
	AccentForeground *string `json:"accentForeground,omitempty" tf:"accent_foreground,omitempty"`

	// Color (hexadecimal) that applies to error messages.
	Danger *string `json:"danger,omitempty" tf:"danger,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the error color.
	DangerForeground *string `json:"dangerForeground,omitempty" tf:"danger_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as dimensions.
	Dimension *string `json:"dimension,omitempty" tf:"dimension,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the dimension color.
	DimensionForeground *string `json:"dimensionForeground,omitempty" tf:"dimension_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as measures.
	Measure *string `json:"measure,omitempty" tf:"measure,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the measure color.
	MeasureForeground *string `json:"measureForeground,omitempty" tf:"measure_foreground,omitempty"`

	// Color (hexadecimal) that applies to visuals and other high emphasis UI.
	PrimaryBackground *string `json:"primaryBackground,omitempty" tf:"primary_background,omitempty"`

	// Color (hexadecimal) of text and other foreground elements that appear over the primary background regions, such as grid lines, borders, table banding, icons, and so on.
	PrimaryForeground *string `json:"primaryForeground,omitempty" tf:"primary_foreground,omitempty"`

	// Color (hexadecimal) that applies to the sheet background and sheet controls.
	SecondaryBackground *string `json:"secondaryBackground,omitempty" tf:"secondary_background,omitempty"`

	// Color (hexadecimal) that applies to any sheet title, sheet control text, or UI that appears over the secondary background.
	SecondaryForeground *string `json:"secondaryForeground,omitempty" tf:"secondary_foreground,omitempty"`

	// Color (hexadecimal) that applies to success messages, for example the check mark for a successful download.
	Success *string `json:"success,omitempty" tf:"success,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the success color.
	SuccessForeground *string `json:"successForeground,omitempty" tf:"success_foreground,omitempty"`

	// Color (hexadecimal) that applies to warning and informational messages.
	Warning *string `json:"warning,omitempty" tf:"warning,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the warning color.
	WarningForeground *string `json:"warningForeground,omitempty" tf:"warning_foreground,omitempty"`
}

type UIColorPaletteObservation struct {

	// Color (hexadecimal) that applies to selected states and buttons.
	Accent *string `json:"accent,omitempty" tf:"accent,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the accent color.
	AccentForeground *string `json:"accentForeground,omitempty" tf:"accent_foreground,omitempty"`

	// Color (hexadecimal) that applies to error messages.
	Danger *string `json:"danger,omitempty" tf:"danger,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the error color.
	DangerForeground *string `json:"dangerForeground,omitempty" tf:"danger_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as dimensions.
	Dimension *string `json:"dimension,omitempty" tf:"dimension,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the dimension color.
	DimensionForeground *string `json:"dimensionForeground,omitempty" tf:"dimension_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as measures.
	Measure *string `json:"measure,omitempty" tf:"measure,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the measure color.
	MeasureForeground *string `json:"measureForeground,omitempty" tf:"measure_foreground,omitempty"`

	// Color (hexadecimal) that applies to visuals and other high emphasis UI.
	PrimaryBackground *string `json:"primaryBackground,omitempty" tf:"primary_background,omitempty"`

	// Color (hexadecimal) of text and other foreground elements that appear over the primary background regions, such as grid lines, borders, table banding, icons, and so on.
	PrimaryForeground *string `json:"primaryForeground,omitempty" tf:"primary_foreground,omitempty"`

	// Color (hexadecimal) that applies to the sheet background and sheet controls.
	SecondaryBackground *string `json:"secondaryBackground,omitempty" tf:"secondary_background,omitempty"`

	// Color (hexadecimal) that applies to any sheet title, sheet control text, or UI that appears over the secondary background.
	SecondaryForeground *string `json:"secondaryForeground,omitempty" tf:"secondary_foreground,omitempty"`

	// Color (hexadecimal) that applies to success messages, for example the check mark for a successful download.
	Success *string `json:"success,omitempty" tf:"success,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the success color.
	SuccessForeground *string `json:"successForeground,omitempty" tf:"success_foreground,omitempty"`

	// Color (hexadecimal) that applies to warning and informational messages.
	Warning *string `json:"warning,omitempty" tf:"warning,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the warning color.
	WarningForeground *string `json:"warningForeground,omitempty" tf:"warning_foreground,omitempty"`
}

type UIColorPaletteParameters struct {

	// Color (hexadecimal) that applies to selected states and buttons.
	// +kubebuilder:validation:Optional
	Accent *string `json:"accent,omitempty" tf:"accent,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the accent color.
	// +kubebuilder:validation:Optional
	AccentForeground *string `json:"accentForeground,omitempty" tf:"accent_foreground,omitempty"`

	// Color (hexadecimal) that applies to error messages.
	// +kubebuilder:validation:Optional
	Danger *string `json:"danger,omitempty" tf:"danger,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the error color.
	// +kubebuilder:validation:Optional
	DangerForeground *string `json:"dangerForeground,omitempty" tf:"danger_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as dimensions.
	// +kubebuilder:validation:Optional
	Dimension *string `json:"dimension,omitempty" tf:"dimension,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the dimension color.
	// +kubebuilder:validation:Optional
	DimensionForeground *string `json:"dimensionForeground,omitempty" tf:"dimension_foreground,omitempty"`

	// Color (hexadecimal) that applies to the names of fields that are identified as measures.
	// +kubebuilder:validation:Optional
	Measure *string `json:"measure,omitempty" tf:"measure,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the measure color.
	// +kubebuilder:validation:Optional
	MeasureForeground *string `json:"measureForeground,omitempty" tf:"measure_foreground,omitempty"`

	// Color (hexadecimal) that applies to visuals and other high emphasis UI.
	// +kubebuilder:validation:Optional
	PrimaryBackground *string `json:"primaryBackground,omitempty" tf:"primary_background,omitempty"`

	// Color (hexadecimal) of text and other foreground elements that appear over the primary background regions, such as grid lines, borders, table banding, icons, and so on.
	// +kubebuilder:validation:Optional
	PrimaryForeground *string `json:"primaryForeground,omitempty" tf:"primary_foreground,omitempty"`

	// Color (hexadecimal) that applies to the sheet background and sheet controls.
	// +kubebuilder:validation:Optional
	SecondaryBackground *string `json:"secondaryBackground,omitempty" tf:"secondary_background,omitempty"`

	// Color (hexadecimal) that applies to any sheet title, sheet control text, or UI that appears over the secondary background.
	// +kubebuilder:validation:Optional
	SecondaryForeground *string `json:"secondaryForeground,omitempty" tf:"secondary_foreground,omitempty"`

	// Color (hexadecimal) that applies to success messages, for example the check mark for a successful download.
	// +kubebuilder:validation:Optional
	Success *string `json:"success,omitempty" tf:"success,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the success color.
	// +kubebuilder:validation:Optional
	SuccessForeground *string `json:"successForeground,omitempty" tf:"success_foreground,omitempty"`

	// Color (hexadecimal) that applies to warning and informational messages.
	// +kubebuilder:validation:Optional
	Warning *string `json:"warning,omitempty" tf:"warning,omitempty"`

	// Color (hexadecimal) that applies to any text or other elements that appear over the warning color.
	// +kubebuilder:validation:Optional
	WarningForeground *string `json:"warningForeground,omitempty" tf:"warning_foreground,omitempty"`
}

// ThemeSpec defines the desired state of Theme
type ThemeSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ThemeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ThemeInitParameters `json:"initProvider,omitempty"`
}

// ThemeStatus defines the observed state of Theme.
type ThemeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ThemeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Theme is the Schema for the Themes API. Manages a QuickSight Theme.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,aws}
type Theme struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.themeId) || (has(self.initProvider) && has(self.initProvider.themeId))",message="spec.forProvider.themeId is a required parameter"
	Spec   ThemeSpec   `json:"spec"`
	Status ThemeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ThemeList contains a list of Themes
type ThemeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Theme `json:"items"`
}

// Repository type metadata.
var (
	Theme_Kind             = "Theme"
	Theme_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Theme_Kind}.String()
	Theme_KindAPIVersion   = Theme_Kind + "." + CRDGroupVersion.String()
	Theme_GroupVersionKind = CRDGroupVersion.WithKind(Theme_Kind)
)

func init() {
	SchemeBuilder.Register(&Theme{}, &ThemeList{})
}
