# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/folder
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    folderId: example-id
    name: example-name
    region: us-east-1
