# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: FolderMembership
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/foldermembership
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    folderIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    memberIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    memberType: DATASET
    region: us-east-1
---
apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/foldermembership
  labels:
    testing.upbound.io/example-name: example
  name: example-folder
  namespace: upbound-system
spec:
  forProvider:
    folderId: example-folder-id
    name: example-folder
    region: us-east-1
---
apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: DataSet
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/dataset
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: upbound-system
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    dataSetId: example-id
    importMode: SPICE
    name: example-name
    physicalTableMap:
      - physicalTableMapId: example-id
        s3Source:
          dataSourceArnSelector:
            matchLabels:
              testing.upbound.io/example-name: uptest-example-qs-datasource-s3
          inputColumns:
            - name: Column1
              type: STRING
          uploadSettings:
            format: JSON
    region: us-east-1
---
apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: DataSource
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3
  namespace: upbound-system
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    dataSourceId: example-s3-role-id
    name: manifest in S3
    parameters:
      s3:
        manifestFileLocation:
          bucketSelector:
            matchLabels:
              testing.upbound.io/example-name: uptest-example-qs-datasource-s3
          key: manifest.json
        roleArnSelector:
          matchLabels:
            testing.upbound.io/example-name: uptest-example-qs-datasource-s3
    region: us-east-1
    type: S3
---
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3-bucket
  namespace: upbound-system
spec:
  forProvider:
    region: us-east-1
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Role
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3-role
  namespace: upbound-system
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Principal": {
              "Service": "quicksight.amazonaws.com"
            }
          }
        ]
      }
---
apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Object
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3-manifest
  namespace: upbound-system
spec:
  forProvider:
    bucketRef:
      name: uptest-example-qs-datasource-s3-bucket
    key: manifest.json
    content: |
      {
        "fileLocations": [
          {
            "URIPrefixes": [
              "https://uptest-example-qs-datasource-s3-bucket.s3.us-east-1.amazonaws.com"
            ]
          }
        ],
        "globalUploadSettings": {
          "format": "CSV",
          "delimiter": ",",
          "textqualifier": "\"",
          "containsHeader": "TRUE"
        }
      }
    region: us-east-1
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3-policy
  namespace: upbound-system
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Action": ["s3:GetObject"],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::uptest-example-qs-datasource-s3-bucket/manifest.json"
          },
          {
            "Action": ["s3:ListBucket"],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::uptest-example-qs-datasource-s3-bucket"
          }
        ]
      }
---
apiVersion: iam.aws.m.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/datasource
  labels:
    testing.upbound.io/example-name: uptest-example-qs-datasource-s3
  name: uptest-example-qs-datasource-s3-rp-attachment
  namespace: upbound-system
spec:
  forProvider:
    policyArnRef:
      name: uptest-example-qs-datasource-s3-policy
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: uptest-example-qs-datasource-s3