# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: quicksight.aws.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/user
    upjet.upbound.io/manual-intervention: "This resource requires a valid email address, manually tested"
  labels:
    testing.upbound.io/example-name: example
  name: example-user
  namespace: upbound-system
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    email: "uptest-example-user@crossplane.io"
    identityType: QUICKSIGHT
    namespace: default
    region: us-east-1
    userName: "uptestExampleUserName"
    userRole: "READER"
