# SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: quicksight.aws.upbound.io/v1beta1
kind: KeyRegistration
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/keyregistration
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    awsAccountId: "${data.aws_account_id}"
    keyRegistration:
    - keyArnRef:
        name: example-key-1
    - keyArnRef:
        name: example-key-2
      defaultKey: true
    region: us-east-1
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/keyregistration
  labels:
    testing.upbound.io/example-name: example
  name: example-key-1
spec:
  forProvider:
    description: QuickSight key registration key 1
    deletionWindowInDays: 7
    region: us-east-1
---
apiVersion: kms.aws.upbound.io/v1beta1
kind: Key
metadata:
  annotations:
    meta.upbound.io/example-id: quicksight/v1beta1/keyregistration
  labels:
    testing.upbound.io/example-name: example
  name: example-key-2
spec:
  forProvider:
    description: QuickSight key registration key 2 (default)
    deletionWindowInDays: 7
    region: us-east-1